MUFI = {
    (0, 86): 'V',  # LATIN CAPITAL LETTER V
    (0, 118): 'V',  # LATIN SMALL LETTER V
    (1, 191): 'V',  # LATIN LETTER WYNN
    (1, 247): 'V',  # LATIN CAPITAL LETTER WYNN
    (22, 161): 'V',  # RUNIC LETTER V
    (29, 32): 'V',  # LATIN LETTER SMALL CAPITAL V
    (30, 126): 'V',  # LATIN CAPITAL LETTER V WITH DOT BELOW
    (30, 127): 'V',  # LATIN SMALL LETTER V WITH DOT BELOW
    (30, 252): 'V',  # LATIN CAPITAL LETTER MIDDLE-WELSH V
    (30, 253): 'V',  # LATIN SMALL LETTER MIDDLE-WELSH V
    (33, 35): 'V',  # VERSICLE
    (44, 125): 'V',  # MODIFIER LETTER CAPITAL V
    (167, 94): 'V',  # LATIN CAPITAL LETTER V WITH DIAGONAL STROKE
    (167, 95): 'V',  # LATIN SMALL LETTER V WITH DIAGONAL STROKE
    (167, 104): 'V',  # LATIN CAPITAL LETTER VEND
    (167, 105): 'V',  # LATIN SMALL LETTER VEND
    (227, 58): 'V',  # LATIN CAPITAL LETTER V WITH ACUTE
    (227, 59): 'V',  # LATIN CAPITAL LETTER V WITH CIRCUMFLEX
    (227, 66): 'V',  # LATIN CAPITAL LETTER V WITH DIAERESIS
    (227, 75): 'V',  # LATIN CAPITAL LETTER V WITH DOUBLE ACUTE
    (227, 76): 'V',  # LATIN CAPITAL LETTER V WITH DOT ABOVE
    (227, 77): 'V',  # LATIN CAPITAL LETTER V WITH MACRON
    (227, 78): 'V',  # LATIN CAPITAL LETTER V WITH VERTICAL LINE ABOVE
    (227, 230): 'V',  # LATIN CAPITAL LETTER INSULAR V (VEND) WITH DOT BELOW
    (227, 231): 'V',  # LATIN CAPITAL LETTER INSULAR V (VEND) WITH DOT ABOVE
    (231, 58): 'V',  # LATIN SMALL LETTER V WITH ACUTE
    (231, 59): 'V',  # LATIN SMALL LETTER V WITH CIRCUMFLEX
    (231, 66): 'V',  # LATIN SMALL LETTER V WITH DIAERESIS
    (231, 67): 'V',  # LATIN SMALL LETTER V WITH RING ABOVE
    (231, 75): 'V',  # LATIN SMALL LETTER V WITH DOUBLE ACUTE
    (231, 76): 'V',  # LATIN SMALL LETTER V WITH DOT ABOVE
    (231, 77): 'V',  # LATIN SMALL LETTER V WITH MACRON
    (231, 78): 'V',  # LATIN SMALL LETTER V WITH BAR
    (231, 79): 'V',  # LATIN SMALL LETTER V WITH VERTICAL LINE ABOVE
    (231, 230): 'V',  # LATIN SMALL LETTER INSULAR V (VEND) WITH DOT BELOW
    (231, 231): 'V',  # LATIN SMALL LETTER INSULAR V (VEND) WITH DOT ABOVE
    (232, 186): 'V',  # LATIN SMALL LETTER V WITH SHORT SLASH
    (232, 187): 'V',  # LATIN SMALL LETTER V WITH SHORT SLASH ABOVE RIGHT
    (232, 188): 'V',  # LATIN SMALL LETTER V WITH TWO SHORT SLASHES ABOVE RIGHT
    (235, 186): 'V',  # LATIN CAPITAL LETTER INSULAR V (VEND) WITH ACUTE
    (235, 187): 'V',  # LATIN SMALL LETTER INSULAR V (VEND) WITH ACUTE
    (238, 248): 'V',  # LATIN ENLARGED LETTER SMALL V
    (247, 178): 'V',  # LATIN CAPITAL LETTER V WITH HIGH OVERLINE (ABOVE CHARACTER)
    (0, 65): 'A',  # LATIN CAPITAL LETTER A
    (0, 97): 'A',  # LATIN SMALL LETTER A
    (0, 170): 'A',  # FEMININE ORDINAL INDICATOR
    (0, 192): 'A',  # LATIN CAPITAL LETTER A WITH GRAVE
    (0, 193): 'A',  # LATIN CAPITAL LETTER A WITH ACUTE
    (0, 194): 'A',  # LATIN CAPITAL LETTER A WITH CIRCUMFLEX
    (0, 195): 'A',  # LATIN CAPITAL LETTER A WITH TILDE
    (0, 196): 'A',  # LATIN CAPITAL LETTER A WITH DIAERESIS
    (0, 197): 'A',  # LATIN CAPITAL LETTER A WITH RING ABOVE
    (0, 198): 'A',  # LATIN CAPITAL LETTER AE
    (0, 224): 'A',  # LATIN SMALL LETTER A WITH GRAVE
    (0, 225): 'A',  # LATIN SMALL LETTER A WITH ACUTE
    (0, 226): 'A',  # LATIN SMALL LETTER A WITH CIRCUMFLEX
    (0, 227): 'A',  # LATIN SMALL LETTER A WITH TILDE
    (0, 228): 'A',  # LATIN SMALL LETTER A WITH DIAERESIS
    (0, 229): 'A',  # LATIN SMALL LETTER A WITH RING ABOVE
    (0, 230): 'A',  # LATIN SMALL LETTER AE
    (1, 0): 'A',  # LATIN CAPITAL LETTER A WITH MACRON
    (1, 1): 'A',  # LATIN SMALL LETTER A WITH MACRON
    (1, 2): 'A',  # LATIN CAPITAL LETTER A WITH BREVE
    (1, 3): 'A',  # LATIN SMALL LETTER A WITH BREVE
    (1, 4): 'A',  # LATIN CAPITAL LETTER A WITH OGONEK
    (1, 5): 'A',  # LATIN SMALL LETTER A WITH OGONEK
    (1, 226): 'A',  # LATIN CAPITAL LETTER AE WITH MACRON
    (1, 227): 'A',  # LATIN SMALL LETTER AE WITH MACRON
    (1, 252): 'A',  # LATIN CAPITAL LETTER AE WITH ACUTE
    (1, 253): 'A',  # LATIN SMALL LETTER AE WITH ACUTE
    (2, 38): 'A',  # LATIN CAPITAL LETTER A WITH DOT ABOVE
    (2, 39): 'A',  # LATIN SMALL LETTER A WITH DOT ABOVE
    (22, 168): 'A',  # RUNIC LETTER ANSUZ A
    (29, 0): 'A',  # LATIN LETTER SMALL CAPITAL A
    (29, 1): 'A',  # LATIN LETTER SMALL CAPITAL AE
    (30, 160): 'A',  # LATIN CAPITAL LETTER A WITH DOT BELOW
    (30, 161): 'A',  # LATIN SMALL LETTER A WITH DOT BELOW
    (30, 162): 'A',  # LATIN CAPITAL LETTER A WITH HOOK ABOVE
    (30, 163): 'A',  # LATIN SMALL LETTER A WITH HOOK ABOVE
    (30, 174): 'A',  # LATIN CAPITAL LETTER A WITH BREVE AND ACUTE
    (30, 175): 'A',  # LATIN SMALL LETTER A WITH BREVE AND ACUTE
    (167, 50): 'A',  # LATIN CAPITAL LETTER AA
    (167, 51): 'A',  # LATIN SMALL LETTER AA
    (167, 52): 'A',  # LATIN CAPITAL LETTER AO
    (167, 53): 'A',  # LATIN SMALL LETTER AO
    (167, 54): 'A',  # LATIN CAPITAL LETTER AU
    (167, 55): 'A',  # LATIN SMALL LETTER AU
    (167, 56): 'A',  # LATIN CAPITAL LETTER AV
    (167, 57): 'A',  # LATIN SMALL LETTER AV
    (167, 58): 'A',  # LATIN CAPITAL LETTER AV WITH HORIZONTAL BAR
    (167, 59): 'A',  # LATIN SMALL LETTER AV WITH HORIZONTAL BAR
    (167, 60): 'A',  # LATIN CAPITAL LETTER AY
    (167, 61): 'A',  # LATIN SMALL LETTER AY
    (224, 4): 'A',  # LATIN CAPITAL LETTER A WITH OGONEK AND ACUTE
    (224, 10): 'A',  # LATIN CAPITAL LETTER A WITH MACRON AND ACUTE
    (224, 16): 'A',  # LATIN CAPITAL LETTER A WITH MACRON AND BREVE
    (224, 37): 'A',  # LATIN CAPITAL LETTER A WITH DOUBLE ACUTE
    (224, 44): 'A',  # LATIN CAPITAL LETTER A WITH LATIN SMALL LETTER E ABOVE
    (224, 51): 'A',  # LATIN CAPITAL LETTER A WITH CURL
    (224, 54): 'A',  # LATIN CAPITAL LETTER AE WITH DOT BELOW
    (224, 58): 'A',  # LATIN CAPITAL LETTER AE WITH MACRON AND ACUTE
    (224, 61): 'A',  # LATIN CAPITAL LETTER AE WITH MACRON AND BREVE
    (224, 63): 'A',  # LATIN CAPITAL LETTER AE WITH BREVE
    (224, 64): 'A',  # LATIN CAPITAL LETTER AE WITH OGONEK
    (224, 65): 'A',  # LATIN CAPITAL LETTER AE WITH DOUBLE ACUTE
    (224, 66): 'A',  # LATIN CAPITAL LETTER AE WITH DIAERESIS
    (224, 67): 'A',  # LATIN CAPITAL LETTER AE WITH DOT ABOVE
    (228, 4): 'A',  # LATIN SMALL LETTER A WITH OGONEK AND ACUTE
    (228, 10): 'A',  # LATIN SMALL LETTER A WITH MACRON AND ACUTE
    (228, 16): 'A',  # LATIN SMALL LETTER A WITH MACRON AND BREVE
    (228, 26): 'A',  # LATIN SMALL LETTER A WITH DIAERESIS AND CIRCUMFLEX
    (228, 29): 'A',  # LATIN SMALL LETTER A WITH DIAERESIS AND DOT BELOW
    (228, 31): 'A',  # LATIN SMALL LETTER A WITH RING ABOVE AND CIRCUMFLEX
    (228, 37): 'A',  # LATIN SMALL LETTER A WITH DOUBLE ACUTE
    (228, 44): 'A',  # LATIN SMALL LETTER A WITH LATIN SMALL LETTER E ABOVE
    (228, 45): 'A',  # LATIN SMALL LETTER A WITH LATIN SMALL LETTER O ABOVE
    (228, 46): 'A',  # LATIN SMALL LETTER A WITH LATIN SMALL LETTER V ABOVE
    (228, 51): 'A',  # LATIN SMALL LETTER A WITH CURL
    (228, 54): 'A',  # LATIN SMALL LETTER AE WITH DOT BELOW
    (228, 58): 'A',  # LATIN SMALL LETTER AE WITH MACRON AND ACUTE
    (228, 61): 'A',  # LATIN SMALL LETTER AE WITH MACRON AND BREVE
    (228, 63): 'A',  # LATIN SMALL LETTER AE WITH BREVE
    (228, 64): 'A',  # LATIN SMALL LETTER AE WITH OGONEK
    (228, 65): 'A',  # LATIN SMALL LETTER AE WITH DOUBLE ACUTE
    (228, 66): 'A',  # LATIN SMALL LETTER AE WITH DIAERESIS
    (228, 67): 'A',  # LATIN SMALL LETTER AE WITH DOT ABOVE
    (232, 209): 'A',  # LATIN SMALL LETTER AE WITH RING ABOVE
    (232, 211): 'A',  # LATIN SMALL LETTER AE WITH OGONEK AND ACUTE
    (232, 213): 'A',  # LATIN SMALL LETTER A WITH DIAGONAL DIAERESIS
    (232, 224): 'A',  # LATIN SMALL LETTER A WITH LATIN SMALL LETTER I ABOVE
    (232, 225): 'A',  # LATIN SMALL LETTER A WITH LATIN SMALL LETTER U ABOVE
    (234, 240): 'A',  # LATIN ENLARGED LETTER SMALL A WITH ACUTE
    (234, 241): 'A',  # LATIN ENLARGED LETTER SMALL LIGATURE AE
    (234, 242): 'A',  # LATIN LIGATURE ENLARGED LETTER SMALL A AND LATIN SMALL LETTER O
    (235, 176): 'A',  # LATIN CAPITAL LIGATURE AV WITH STROKE AND ACUTE
    (235, 177): 'A',  # LATIN SMALL LIGATURE AV WITH STROKE AND ACUTE
    (235, 192): 'A',  # LATIN CAPITAL LIGATURE AO WITH DOUBLE ACUTE
    (235, 193): 'A',  # LATIN SMALL LIGATURE AO WITH DOUBLE ACUTE
    (235, 194): 'A',  # LATIN CAPITAL LIGATURE AV WITH DOUBLE ACUTE
    (235, 195): 'A',  # LATIN SMALL LIGATURE AV WITH DOUBLE ACUTE
    (235, 234): 'A',  # LATIN CAPITAL LETTER AE WITH CURL
    (235, 235): 'A',  # LATIN SMALL LETTER AE WITH CURL
    (235, 240): 'A',  # LATIN CAPITAL LIGATURE AV WITH OGONEK
    (235, 241): 'A',  # LATIN SMALL LIGATURE AV WITH OGONEK
    (235, 244): 'A',  # LATIN CAPITAL LETTER A WITH DOT ABOVE AND ACUTE
    (235, 245): 'A',  # LATIN SMALL LETTER A WITH DOT ABOVE AND ACUTE
    (238, 224): 'A',  # LATIN ENLARGED LETTER SMALL A
    (239, 160): 'A',  # LATIN SMALL LIGATURE AA CLOSED FORM
    (239, 161): 'A',  # LATIN SMALL LIGATURE NECKLESS A E
    (239, 162): 'A',  # LATIN SMALL LIGATURE NECKLESS A V
    (239, 163): 'A',  # LATIN SMALL LIGATURE AF
    (239, 164): 'A',  # LATIN SMALL LIGATURE A INSULAR F
    (239, 165): 'A',  # LATIN SMALL LIGATURE AG
    (239, 166): 'A',  # LATIN SMALL LIGATURE AL
    (239, 167): 'A',  # LATIN SMALL LIGATURE AN
    (239, 168): 'A',  # LATIN SMALL LIGATURE A SMALL CAPITAL N
    (239, 169): 'A',  # LATIN SMALL LIGATURE AP
    (239, 170): 'A',  # LATIN SMALL LIGATURE AR
    (239, 171): 'A',  # LATIN SMALL LIGATURE A SMALL CAPITAL R
    (239, 172): 'A',  # LATIN SMALL LIGATURE A THORN
    (239, 174): 'A',  # LATIN CAPITAL LIGATURE NECKLESS A E
    (239, 219): 'A',  # LATIN CAPITAL LETTER AE WITH DOT ABOVE AND ACUTE
    (239, 220): 'A',  # LATIN SMALL LETTER AE WITH DOT ABOVE AND ACUTE
    (239, 222): 'A',  # LATIN ENLARGED LETTER SMALL LIGATURE AO
    (239, 223): 'A',  # LATIN ENLARGED LETTER SMALL LIGATURE AA
    (239, 224): 'A',  # LATIN CAPITAL LIGATURE AA WITH ACUTE
    (239, 225): 'A',  # LATIN SMALL LIGATURE AA WITH ACUTE
    (239, 226): 'A',  # LATIN CAPITAL LIGATURE AO WITH ACUTE
    (239, 227): 'A',  # LATIN SMALL LIGATURE AO WITH ACUTE
    (239, 228): 'A',  # LATIN CAPITAL LIGATURE AU WITH ACUTE
    (239, 229): 'A',  # LATIN SMALL LIGATURE AU WITH ACUTE
    (239, 230): 'A',  # LATIN CAPITAL LIGATURE AV WITH ACUTE
    (239, 231): 'A',  # LATIN SMALL LIGATURE AV WITH ACUTE
    (239, 234): 'A',  # LATIN CAPITAL LIGATURE AA WITH DOUBLE ACUTE
    (239, 235): 'A',  # LATIN SMALL LIGATURE AA WITH DOUBLE ACUTE
    (239, 238): 'A',  # LATIN CAPITAL LIGATURE AA WITH DOT ABOVE
    (239, 239): 'A',  # LATIN SMALL LIGATURE AA WITH DOT ABOVE
    (239, 240): 'A',  # LATIN CAPITAL LIGATURE AY WITH DOT ABOVE
    (239, 241): 'A',  # LATIN SMALL LIGATURE AY WITH DOT ABOVE
    (239, 242): 'A',  # LATIN CAPITAL LIGATURE AA WITH DOT BELOW
    (239, 243): 'A',  # LATIN SMALL LIGATURE AA WITH DOT BELOW
    (239, 244): 'A',  # LATIN CAPITAL LIGATURE AO WITH DOT BELOW
    (239, 245): 'A',  # LATIN SMALL LIGATURE AO WITH DOT BELOW
    (239, 246): 'A',  # LATIN CAPITAL LIGATURE AU WITH DOT BELOW
    (239, 247): 'A',  # LATIN SMALL LIGATURE AU WITH DOT BELOW
    (239, 248): 'A',  # LATIN CAPITAL LIGATURE AV WITH DOT BELOW
    (239, 249): 'A',  # LATIN SMALL LIGATURE AV WITH DOT BELOW
    (239, 250): 'A',  # LATIN CAPITAL LIGATURE AY WITH DOT BELOW
    (239, 251): 'A',  # LATIN SMALL LIGATURE AY WITH DOT BELOW
    (239, 254): 'A',  # LATIN CAPITAL LIGATURE AA WITH DIAERESIS
    (239, 255): 'A',  # LATIN SMALL LIGATURE AA WITH DIAERESIS
    (241, 58): 'A',  # LATIN CAPITAL LETTER A SQUARE FORM
    (242, 0): 'A',  # LATIN SMALL LETTER A INSULAR FORM
    (242, 1): 'A',  # LATIN CAPITAL LETTER A INSULAR FORM
    (242, 2): 'A',  # LATIN SMALL LETTER OPEN A CAROLINGIAN FORM
    (242, 3): 'A',  # LATIN SMALL LETTER CLOSED A GOTHIC FORM
    (242, 4): 'A',  # LATIN SMALL LETTER AE WITH RIGHT UPPER LOOP
    (242, 5): 'A',  # LATIN CAPITAL LIGATURE AO NECKLESS
    (242, 6): 'A',  # LATIN SMALL LIGATURE AO NECKLESS
    (242, 20): 'A',  # LATIN SMALL LETTER A UNCIAL FORM
    (242, 21): 'A',  # LATIN SMALL LETTER NECKLESS A
    (32, 34): '',  # BULLET
    (32, 35): '',  # TRIANGULAR BULLET
    (33, 144): '',  # LEFTWARDS ARROW
    (33, 145): '',  # UPWARDS ARROW
    (33, 146): '',  # RIGHTWARDS ARROW
    (33, 147): '',  # DOWNWARDS ARROW
    (37, 170): '',  # BLACK SMALL SQUARE
    (37, 171): '',  # WHITE SMALL SQUARE
    (37, 185): '',  # WHITE RIGHT-POINTING SMALL TRIANGLE
    (37, 195): '',  # WHITE LEFT-POINTING SMALL TRIANGLE
    (37, 204): '',  # DOTTED CIRCLE
    (0, 67): 'C',  # LATIN CAPITAL LETTER C
    (0, 99): 'C',  # LATIN SMALL LETTER C
    (0, 199): 'C',  # LATIN CAPITAL LETTER C WITH CEDILLA
    (0, 231): 'C',  # LATIN SMALL LETTER C WITH CEDILLA
    (1, 6): 'C',  # LATIN CAPITAL LETTER C WITH ACUTE
    (1, 7): 'C',  # LATIN SMALL LETTER C WITH ACUTE
    (1, 10): 'C',  # LATIN CAPITAL LETTER C WITH DOT ABOVE
    (1, 11): 'C',  # LATIN SMALL LETTER C WITH DOT ABOVE
    (29, 4): 'C',  # LATIN LETTER SMALL CAPITAL C
    (33, 132): 'C',  # LATIN ABBREVIATION SIGN SMALL CON
    (224, 102): 'C',  # LATIN CAPITAL LETTER C WITH DOT BELOW
    (224, 118): 'C',  # LATIN CAPITAL LETTER C WITH OGONEK
    (228, 102): 'C',  # LATIN SMALL LETTER C WITH DOT BELOW
    (228, 118): 'C',  # LATIN SMALL LETTER C WITH OGONEK
    (238, 196): 'C',  # LATIN SMALL LIGATURE CK
    (238, 197): 'C',  # LATIN SMALL LIGATURE CT
    (238, 226): 'C',  # LATIN ENLARGED LETTER SMALL C
    (241, 6): 'C',  # LATIN CAPITAL LETTER C SQUARE FORM
    (241, 152): 'C',  # LATIN SMALL LETTER C WITH CURL
    (241, 187): 'C',  # LATIN SMALL LIGATURE CH
    (242, 254): 'C',  # ROMAN NUMERAL CAPITAL C WITH TWO BARS
    (242, 255): 'C',  # ROMAN NUMERAL SMALL C WITH TWO BARS
    (247, 181): 'C',  # LATIN CAPITAL LETTER C WITH HIGH OVERLINE (ABOVE CHARACTER)
    (0, 83): 'S',  # LATIN CAPITAL LETTER S
    (0, 115): 'S',  # LATIN SMALL LETTER S
    (0, 223): 'S',  # LATIN SMALL LETTER SHARP S
    (1, 90): 'S',  # LATIN CAPITAL LETTER S WITH ACUTE
    (1, 91): 'S',  # LATIN SMALL LETTER S WITH ACUTE
    (1, 127): 'S',  # LATIN SMALL LETTER LONG S
    (30, 96): 'S',  # LATIN CAPITAL LETTER S WITH DOT ABOVE
    (30, 97): 'S',  # LATIN SMALL LETTER S WITH DOT ABOVE
    (30, 98): 'S',  # LATIN CAPITAL LETTER S WITH DOT BELOW
    (30, 99): 'S',  # LATIN SMALL LETTER S WITH DOT BELOW
    (30, 156): 'S',  # LATIN SMALL LETTER LONG S WITH DIAGONAL STROKE
    (30, 157): 'S',  # LATIN SMALL LETTER LONG S WITH HIGH STROKE
    (30, 158): 'S',  # LATIN CAPITAL LETTER SHARP S
    (167, 49): 'S',  # LATIN LETTER SMALL CAPITAL S
    (167, 132): 'S',  # LATIN CAPITAL LETTER INSULAR S
    (167, 133): 'S',  # LATIN SMALL LETTER INSULAR S
    (231, 158): 'S',  # LATIN SMALL LETTER LONG S WITH MEDIUM-HIGH OVERLINE (ACROSS ASCENDER)
    (231, 194): 'S',  # LATIN SMALL LETTER LONG S WITH DOT BELOW
    (232, 183): 'S',  # LATIN SMALL LETTER LONG S WITH FLOURISH
    (232, 184): 'S',  # LATIN SMALL LETTER LONG S WITH SLANTED DESCENDING STROKE
    (232, 223): 'S',  # LATIN SMALL LIGATURE LONG S L WITH STROKE
    (234, 218): 'S',  # LATIN SMALL LIGATURE LONG S DESCENDING T
    (235, 160): 'S',  # LATIN SMALL LIGATURE LONG S A WITH DIAERESIS
    (235, 161): 'S',  # LATIN SMALL LIGATURE LONG S H
    (235, 162): 'S',  # LATIN SMALL LIGATURE LONG S I
    (235, 163): 'S',  # LATIN SMALL LIGATURE LONG S L
    (235, 164): 'S',  # LATIN SMALL LIGATURE LONG S O WITH DIAERESIS
    (235, 165): 'S',  # LATIN SMALL LIGATURE LONG S P
    (235, 166): 'S',  # LATIN SMALL LIGATURE LONG S LONG S
    (235, 167): 'S',  # LATIN SMALL LIGATURE LONG S LONG S I
    (235, 168): 'S',  # LATIN SMALL LIGATURE LONG S LONG S L
    (235, 169): 'S',  # LATIN SMALL LIGATURE LONG S TI
    (235, 170): 'S',  # LATIN SMALL LIGATURE LONG S TR
    (235, 171): 'S',  # LATIN SMALL LIGATURE LONG S U WITH DIAERESIS
    (235, 172): 'S',  # LATIN SMALL LIGATURE LONG S INSULAR V
    (235, 175): 'S',  # LATIN SMALL LETTER LONG S WITH ACUTE
    (238, 223): 'S',  # LATIN ENLARGED LETTER SMALL LONG S
    (238, 244): 'S',  # LATIN ENLARGED LETTER SMALL S
    (239, 35): 'S',  # LATIN LETTER SMALL CAPITAL S WITH DOT ABOVE
    (239, 44): 'S',  # LATIN LETTER SMALL CAPITAL S WITH DOT BELOW
    (241, 38): 'S',  # LATIN CAPITAL LETTER S CLOSED FORM
    (241, 39): 'S',  # LATIN SMALL LETTER LONG S DESCENDING
    (241, 40): 'S',  # LATIN SMALL LETTER S CLOSED FORM
    (244, 250): 'S',  # LATIN SMALL LIGATURE LONG S CH
    (244, 251): 'S',  # LATIN SMALL LIGATURE LONG S J
    (244, 252): 'S',  # LATIN SMALL LIGATURE LONG S K
    (244, 253): 'S',  # LATIN SMALL LIGATURE LONG S S
    (244, 254): 'S',  # LATIN SMALL LIGATURE LONG S LONG S K
    (244, 255): 'S',  # LATIN SMALL LIGATURE LONG S LONG S T
    (251, 5): 'S',  # LATIN SMALL LIGATURE LONG S T
    (251, 6): 'S',  # LATIN SMALL LIGATURE ST
    (0, 90): 'Z',  # LATIN CAPITAL LETTER Z
    (0, 122): 'Z',  # LATIN SMALL LETTER Z
    (1, 123): 'Z',  # LATIN CAPITAL LETTER Z WITH DOT ABOVE
    (1, 124): 'Z',  # LATIN SMALL LETTER Z WITH DOT ABOVE
    (1, 181): 'Z',  # LATIN CAPITAL LETTER Z WITH STROKE
    (1, 182): 'Z',  # LATIN SMALL LETTER Z WITH STROKE
    (29, 34): 'Z',  # LATIN LETTER SMALL CAPITAL Z
    (30, 146): 'Z',  # LATIN CAPITAL LETTER Z WITH DOT BELOW
    (30, 147): 'Z',  # LATIN SMALL LETTER Z WITH DOT BELOW
    (167, 98): 'Z',  # LATIN CAPITAL LETTER VISIGOTHIC Z
    (167, 99): 'Z',  # LATIN SMALL LETTER VISIGOTHIC Z
    (238, 252): 'Z',  # LATIN ENLARGED LETTER SMALL Z
    (0, 85): 'U',  # LATIN CAPITAL LETTER U
    (0, 117): 'U',  # LATIN SMALL LETTER U
    (0, 217): 'U',  # LATIN CAPITAL LETTER U WITH GRAVE
    (0, 218): 'U',  # LATIN CAPITAL LETTER U WITH ACUTE
    (0, 219): 'U',  # LATIN CAPITAL LETTER U WITH CIRCUMFLEX
    (0, 220): 'U',  # LATIN CAPITAL LETTER U WITH DIAERESIS
    (0, 249): 'U',  # LATIN SMALL LETTER U WITH GRAVE
    (0, 250): 'U',  # LATIN SMALL LETTER U WITH ACUTE
    (0, 251): 'U',  # LATIN SMALL LETTER U WITH CIRCUMFLEX
    (0, 252): 'U',  # LATIN SMALL LETTER U WITH DIAERESIS
    (1, 106): 'U',  # LATIN CAPITAL LETTER U WITH MACRON
    (1, 107): 'U',  # LATIN SMALL LETTER U WITH MACRON
    (1, 108): 'U',  # LATIN CAPITAL LETTER U WITH BREVE
    (1, 109): 'U',  # LATIN SMALL LETTER U WITH BREVE
    (1, 110): 'U',  # LATIN CAPITAL LETTER U WITH RING ABOVE
    (1, 111): 'U',  # LATIN SMALL LETTER U WITH RING ABOVE
    (1, 112): 'U',  # LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
    (1, 113): 'U',  # LATIN SMALL LETTER U WITH DOUBLE ACUTE
    (1, 114): 'U',  # LATIN CAPITAL LETTER U WITH OGONEK
    (1, 115): 'U',  # LATIN SMALL LETTER U WITH OGONEK
    (1, 211): 'U',  # LATIN CAPITAL LETTER U WITH CARON
    (1, 212): 'U',  # LATIN SMALL LETTER U WITH CARON
    (1, 213): 'U',  # LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
    (1, 214): 'U',  # LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
    (2, 137): 'U',  # LATIN SMALL LETTER U BAR
    (22, 162): 'U',  # RUNIC LETTER URUZ UR U
    (29, 28): 'U',  # LATIN LETTER SMALL CAPITAL U
    (29, 107): 'U',  # LATIN SMALL LETTER UE
    (30, 228): 'U',  # LATIN CAPITAL LETTER U WITH DOT BELOW
    (30, 229): 'U',  # LATIN SMALL LETTER U WITH DOT BELOW
    (30, 230): 'U',  # LATIN CAPITAL LETTER U WITH HOOK ABOVE
    (30, 231): 'U',  # LATIN SMALL LETTER U WITH HOOK ABOVE
    (227, 9): 'U',  # LATIN CAPITAL LETTER U WITH MACRON AND ACUTE
    (227, 11): 'U',  # LATIN CAPITAL LETTER U WITH MACRON AND BREVE
    (227, 21): 'U',  # LATIN CAPITAL LETTER U WITH DOT ABOVE
    (227, 23): 'U',  # LATIN CAPITAL LETTER U WITH DIAERESIS AND CIRCUMFLEX
    (227, 36): 'U',  # LATIN CAPITAL LETTER U WITH VERTICAL LINE ABOVE
    (227, 43): 'U',  # LATIN CAPITAL LETTER U WITH LATIN SMALL LETTER E ABOVE
    (227, 45): 'U',  # LATIN CAPITAL LETTER U WITH LATIN SMALL LETTER O ABOVE
    (227, 49): 'U',  # LATIN CAPITAL LETTER U WITH CURL
    (231, 9): 'U',  # LATIN SMALL LETTER U WITH MACRON AND ACUTE
    (231, 11): 'U',  # LATIN SMALL LETTER U WITH MACRON AND BREVE
    (231, 21): 'U',  # LATIN SMALL LETTER U WITH DOT ABOVE
    (231, 23): 'U',  # LATIN SMALL LETTER U WITH DIAERESIS AND CIRCUMFLEX
    (231, 36): 'U',  # LATIN SMALL LETTER U WITH VERTICAL LINE ABOVE
    (231, 39): 'U',  # LATIN SMALL LETTER U WITH INVERTED BREVE BELOW
    (231, 43): 'U',  # LATIN SMALL LETTER U WITH LATIN SMALL LETTER E ABOVE
    (231, 44): 'U',  # LATIN SMALL LETTER U WITH LATIN SMALL LETTER I ABOVE
    (231, 45): 'U',  # LATIN SMALL LETTER U WITH LATIN SMALL LETTER O ABOVE
    (231, 49): 'U',  # LATIN SMALL LETTER U WITH CURL
    (232, 198): 'U',  # LATIN CAPITAL LIGATURE UU
    (232, 199): 'U',  # LATIN SMALL LIGATURE UU
    (232, 200): 'U',  # LATIN CAPITAL LIGATURE UE
    (232, 201): 'U',  # LATIN SMALL LIGATURE UE
    (232, 235): 'U',  # LATIN SMALL LETTER U WITH LATIN SMALL LETTER A ABOVE
    (232, 236): 'U',  # LATIN SMALL LETTER U WITH LATIN SMALL LETTER V ABOVE
    (232, 237): 'U',  # LATIN SMALL LETTER U WITH LATIN SMALL LETTER W ABOVE
    (235, 191): 'U',  # LATIN SMALL LETTER U WITH CURLY BAR ABOVE
    (235, 254): 'U',  # LATIN CAPITAL LETTER U WITH DOT ABOVE AND ACUTE
    (235, 255): 'U',  # LATIN SMALL LETTER U WITH DOT ABOVE AND ACUTE
    (238, 247): 'U',  # LATIN ENLARGED LETTER SMALL U
    (239, 216): 'U',  # LATIN SMALL LIGATURE UU WITH DOUBLE ACUTE
    (239, 217): 'U',  # LATIN CAPITAL LIGATURE UU WITH DOUBLE ACUTE
    (0, 68): 'D',  # LATIN CAPITAL LETTER D
    (0, 100): 'D',  # LATIN SMALL LETTER D
    (0, 208): 'D',  # LATIN CAPITAL LETTER ETH
    (0, 240): 'D',  # LATIN SMALL LETTER ETH
    (1, 16): 'D',  # LATIN CAPITAL LETTER D WITH STROKE
    (1, 17): 'D',  # LATIN SMALL LETTER D WITH STROKE
    (2, 86): 'D',  # LATIN SMALL LETTER D WITH TAIL
    (22, 167): 'D',  # RUNIC LETTER ETH
    (29, 5): 'D',  # LATIN LETTER SMALL CAPITAL D
    (29, 6): 'D',  # LATIN LETTER SMALL CAPITAL ETH
    (30, 10): 'D',  # LATIN CAPITAL LETTER D WITH DOT ABOVE
    (30, 11): 'D',  # LATIN SMALL LETTER D WITH DOT ABOVE
    (30, 12): 'D',  # LATIN CAPITAL LETTER D WITH DOT BELOW
    (30, 13): 'D',  # LATIN SMALL LETTER D WITH DOT BELOW
    (30, 159): 'D',  # LATIN SMALL LETTER DELTA
    (167, 113): 'D',  # LATIN SMALL LETTER DUM
    (167, 121): 'D',  # LATIN CAPITAL LETTER INSULAR D
    (167, 122): 'D',  # LATIN SMALL LETTER INSULAR D
    (224, 119): 'D',  # LATIN CAPITAL LETTER D WITH ACUTE
    (224, 143): 'D',  # LATIN CAPITAL LETTER ETH WITH DOT BELOW
    (228, 119): 'D',  # LATIN SMALL LETTER D WITH ACUTE
    (228, 143): 'D',  # LATIN SMALL LETTER ETH WITH DOT BELOW
    (228, 145): 'D',  # LATIN SMALL LETTER D WITH MEDIUM-HIGH OVERLINE (ACROSS ASCENDER)
    (235, 178): 'D',  # LATIN SMALL LETTER D ROTUNDA WITH ACUTE
    (235, 209): 'D',  # LATIN SMALL LETTER D ROTUNDA WITH DOT ABOVE
    (235, 210): 'D',  # LATIN LETTER SMALL CAPITAL D WITH DOT ABOVE
    (238, 198): 'D',  # LATIN SMALL LIGATURE DD ROTUNDA
    (238, 227): 'D',  # LATIN ENLARGED LETTER SMALL D
    (238, 228): 'D',  # LATIN ENLARGED LETTER D ROTUNDA
    (238, 229): 'D',  # LATIN ENLARGED LETTER SMALL ETH
    (239, 38): 'D',  # LATIN LETTER SMALL CAPITAL D WITH DOT BELOW
    (241, 147): 'D',  # LATIN SMALL LETTER D WITH CURL
    (247, 182): 'D',  # LATIN CAPITAL LETTER D WITH HIGH OVERLINE (ABOVE CHARACTER)
    (0, 32): '',  # SPACE
    (0, 127): '',  # DELETE
    (0, 160): '',  # NO-BREAK SPACE
    (0, 173): '',  # SOFT HYPHEN
    (32, 0): '',  # EN QUAD
    (32, 1): '',  # EM QUAD
    (32, 2): '',  # EN SPACE
    (32, 3): '',  # EM SPACE
    (32, 4): '',  # THREE-PER-EM SPACE
    (32, 5): '',  # FOUR-PER-EM SPACE
    (32, 6): '',  # SIX-PER-EM SPACE
    (32, 7): '',  # FIGURE SPACE
    (32, 8): '',  # PUNCTUATION SPACE
    (32, 9): '',  # THIN SPACE
    (32, 10): '',  # HAIR SPACE
    (32, 11): '',  # ZERO WIDTH SPACE
    (32, 47): '',  # NARROW NO-BREAK SPACE
    (0, 66): 'B',  # LATIN CAPITAL LETTER B
    (0, 98): 'B',  # LATIN SMALL LETTER B
    (1, 128): 'B',  # LATIN SMALL LETTER B WITH STROKE
    (2, 153): 'B',  # LATIN LETTER SMALL CAPITAL B
    (30, 2): 'B',  # LATIN CAPITAL LETTER B WITH DOT ABOVE
    (30, 3): 'B',  # LATIN SMALL LETTER B WITH DOT ABOVE
    (30, 4): 'B',  # LATIN CAPITAL LETTER B WITH DOT BELOW
    (30, 5): 'B',  # LATIN SMALL LETTER B WITH DOT BELOW
    (224, 68): 'B',  # LATIN CAPITAL LETTER B WITH ACUTE
    (228, 68): 'B',  # LATIN SMALL LETTER B WITH ACUTE
    (228, 77): 'B',  # LATIN SMALL LETTER B WITH MEDIUM-HIGH OVERLINE (ACROSS ASCENDER)
    (235, 208): 'B',  # LATIN LETTER SMALL CAPITAL B WITH DOT ABOVE
    (238, 194): 'B',  # LATIN SMALL LIGATURE BB
    (238, 195): 'B',  # LATIN SMALL LIGATURE BG
    (238, 225): 'B',  # LATIN ENLARGED LETTER SMALL B
    (239, 37): 'B',  # LATIN LETTER SMALL CAPITAL B WITH DOT BELOW
    (3, 0): '',  # COMBINING GRAVE ACCENT
    (3, 1): '',  # COMBINING ACUTE ACCENT
    (3, 2): '',  # COMBINING CIRCUMFLEX ACCENT
    (3, 3): '',  # COMBINING TILDE
    (3, 4): '',  # COMBINING MACRON
    (3, 5): '',  # COMBINING OVERLINE
    (3, 6): '',  # COMBINING BREVE
    (3, 7): '',  # COMBINING DOT ABOVE
    (3, 8): '',  # COMBINING DIAERESIS
    (3, 9): '',  # COMBINING HOOK ABOVE
    (3, 10): '',  # COMBINING RING ABOVE
    (3, 11): '',  # COMBINING DOUBLE ACUTE ACCENT
    (3, 13): '',  # COMBINING VERTICAL LINE ABOVE
    (3, 14): '',  # COMBINING DOUBLE VERTICAL LINE ABOVE
    (3, 21): '',  # COMBINING COMMA ABOVE RIGHT
    (3, 35): '',  # COMBINING DOT BELOW
    (3, 39): '',  # COMBINING CEDILLA
    (3, 40): '',  # COMBINING OGONEK
    (3, 50): '',  # COMBINING LOW LINE
    (3, 51): '',  # COMBINING DOUBLE LOW LINE
    (3, 54): '',  # COMBINING LONG STROKE OVERLAY
    (3, 62): '',  # COMBINING VERTICAL TILDE
    (3, 63): '',  # COMBINING DOUBLE OVERLINE
    (3, 89): '',  # COMBINING ASTERISK BELOW
    (3, 91): '',  # COMBINING ZIGZAG ABOVE
    (3, 92): '',  # COMBINING DOUBLE BREVE BELOW
    (3, 96): '',  # COMBINING DOUBLE TILDE
    (3, 99): '',  # COMBINING LATIN SMALL LETTER A
    (3, 100): '',  # COMBINING LATIN SMALL LETTER E
    (3, 101): '',  # COMBINING LATIN SMALL LETTER I
    (3, 102): '',  # COMBINING LATIN SMALL LETTER O
    (3, 103): '',  # COMBINING LATIN SMALL LETTER U
    (3, 104): '',  # COMBINING LATIN SMALL LETTER C
    (3, 105): '',  # COMBINING LATIN SMALL LETTER D
    (3, 106): '',  # COMBINING LATIN SMALL LETTER H
    (3, 107): '',  # COMBINING LATIN SMALL LETTER M
    (3, 108): '',  # COMBINING LATIN SMALL LETTER R
    (3, 109): '',  # COMBINING LATIN SMALL LETTER T
    (3, 110): '',  # COMBINING LATIN SMALL LETTER V
    (3, 111): '',  # COMBINING LATIN SMALL LETTER X
    (29, 205): '',  # COMBINING DOUBLE CIRCUMFLEX ABOVE
    (29, 206): '',  # COMBINING OGONEK ABOVE
    (29, 207): '',  # COMBINING ZIGZAG BELOW
    (29, 208): '',  # COMBINING IS BELOW
    (29, 209): '',  # COMBINING UR ABOVE
    (29, 210): '',  # COMBINING US ABOVE
    (29, 211): '',  # COMBINING LATIN SMALL LETTER FLATTENED OPEN A ABOVE
    (29, 212): '',  # COMBINING LATIN SMALL LETTER AE
    (29, 213): '',  # COMBINING LATIN SMALL LIGATURE AO
    (29, 214): '',  # COMBINING LATIN SMALL LIGATURE AV
    (29, 215): '',  # COMBINING LATIN SMALL LETTER C CEDILLA
    (29, 216): '',  # COMBINING LATIN LETTER INSULAR D
    (29, 217): '',  # COMBINING LATIN SMALL LETTER ETH
    (29, 218): '',  # COMBINING LATIN SMALL LETTER G
    (29, 219): '',  # COMBINING LATIN LETTER SMALL CAPITAL G
    (29, 220): '',  # COMBINING LATIN SMALL LETTER K
    (29, 221): '',  # COMBINING LATIN SMALL LETTER L
    (29, 222): '',  # COMBINING LATIN LETTER SMALL CAPITAL L
    (29, 223): '',  # COMBINING LATIN LETTER SMALL CAPITAL M
    (29, 224): '',  # COMBINING LATIN SMALL LETTER N
    (29, 225): '',  # COMBINING LATIN LETTER SMALL CAPITAL N
    (29, 226): '',  # COMBINING LATIN LETTER SMALL CAPITAL R
    (29, 227): '',  # COMBINING LATIN SMALL LETTER R ROTUNDA
    (29, 228): '',  # COMBINING LATIN SMALL LETTER S
    (29, 229): '',  # COMBINING LATIN SMALL LETTER LONG S
    (29, 230): '',  # COMBINING LATIN SMALL LETTER Z
    (240, 10): '',  # COMBINING HIGH MACRON WITH FIXED HEIGHT (PART-WIDTH)
    (240, 11): '',  # COMBINING MEDIUM-HIGH MACRON WITH FIXED HEIGHT (PART-WIDTH)
    (240, 12): '',  # COMBINING HIGH OVERLINE WITH FIXED HEIGHT (FULL-WIDTH)
    (240, 13): '',  # COMBINING MEDIUM-HIGH OVERLINE WITH FIXED HEIGHT (FULL-WIDTH)
    (240, 18): '',  # COMBINING LATIN SMALL LETTER B
    (240, 19): '',  # COMBINING LATIN LETTER SMALL CAPITAL B
    (240, 22): '',  # COMBINING LATIN LETTER SMALL CAPITAL D
    (240, 23): '',  # COMBINING LATIN SMALL LETTER F
    (240, 28): '',  # COMBINING LATIN LETTER SMALL CAPITAL K
    (240, 37): '',  # COMBINING LATIN SMALL LETTER P
    (240, 42): '',  # COMBINING LATIN LETTER SMALL CAPITAL T
    (240, 43): '',  # COMBINING LATIN SMALL LETTER Y
    (240, 47): '',  # COMBINING LATIN SMALL LETTER DOTLESS I
    (240, 48): '',  # COMBINING LATIN SMALL LETTER J
    (240, 49): '',  # COMBINING LATIN SMALL LETTER DOTLESS J
    (240, 50): '',  # COMBINING LATIN LETTER SMALL O WITH STROKE
    (240, 51): '',  # COMBINING LATIN SMALL LETTER Q
    (240, 54): '',  # COMBINING LATIN SMALL LIGATURE AN
    (240, 56): '',  # COMBINING LATIN SMALL LIGATURE AR
    (240, 58): '',  # COMBINING LATIN SMALL LIGATURE A SMALL CAPITAL N
    (240, 59): '',  # COMBINING LATIN LETTER T ROTUNDA
    (240, 60): '',  # COMBINING LATIN SMALL LETTER W
    (240, 61): '',  # COMBINING LATIN SMALL LETTER THORN
    (240, 62): '',  # COMBINING LATIN SMALL LETTER O R ROTUNDA
    (240, 63): '',  # COMBINING LATIN SMALL LETTER O RUM
    (240, 64): '',  # COMBINING LATIN SMALL LETTER RUM
    (241, 48): '',  # COMBINING LATIN SMALL LIGATURE A SMALL CAPITAL R
    (241, 53): '',  # COMBINING LATIN SMALL LETTER E WITH OGONEK
    (241, 54): '',  # COMBINING LATIN SMALL LETTER E WITH MACRON
    (241, 62): '',  # COMBINING LATIN SMALL LETTER O WITH OGONEK
    (241, 63): '',  # COMBINING LATIN SMALL LETTER O WITH MACRON
    (241, 83): '',  # COMBINING ABBREVIATION MARK SUPERSCRIPT UR ROUND R FORM
    (241, 192): '',  # COMBINING ABBREVIATION MARK BAR ABOVE WITH DOT
    (241, 193): '',  # COMBINING ABBREVIATION MARK SUPERSCRIPT RA OPEN A FORM WITH BAR ABOVE
    (241, 194): '',  # COMBINING ABBREVIATION MARK SUPERSCRIPT UR LEMNISKATE FORM
    (241, 197): '',  # COMBINING CURL HIGH POSITION
    (241, 199): '',  # COMBINING ABBREVIATION MARK ZIGZAG ABOVE ANGLE FORM
    (241, 200): '',  # COMBINING ABBREVIATION MARK ZIGZAG ABOVE CURLY FORM
    (241, 202): '',  # COMBINING DOT ABOVE HIGH POSITION
    (241, 204): '',  # COMBINING CURLY BAR ABOVE
    (241, 252): '',  # COMBINING TRIPLE BREVE BELOW
    (0, 71): 'G',  # LATIN CAPITAL LETTER G
    (0, 103): 'G',  # LATIN SMALL LETTER G
    (1, 32): 'G',  # LATIN CAPITAL LETTER G WITH DOT ABOVE
    (1, 33): 'G',  # LATIN SMALL LETTER G WITH DOT ABOVE
    (1, 228): 'G',  # LATIN CAPITAL LETTER G WITH STROKE
    (1, 229): 'G',  # LATIN SMALL LETTER G WITH STROKE
    (1, 244): 'G',  # LATIN CAPITAL LETTER G WITH ACUTE
    (1, 245): 'G',  # LATIN SMALL LETTER G WITH ACUTE
    (2, 97): 'G',  # LATIN SMALL LETTER SCRIPT G
    (2, 98): 'G',  # LATIN LETTER SMALL CAPITAL G
    (29, 121): 'G',  # LATIN SMALL LETTER INSULAR G
    (167, 125): 'G',  # LATIN CAPITAL LETTER INSULAR G
    (167, 126): 'G',  # LATIN CAPITAL LETTER TURNED INSULAR G
    (167, 127): 'G',  # LATIN SMALL LETTER TURNED INSULAR G
    (225, 1): 'G',  # LATIN CAPITAL LETTER G WITH DOT BELOW
    (229, 1): 'G',  # LATIN SMALL LETTER G WITH DOT BELOW
    (234, 208): 'G',  # LATIN SMALL LIGATURE GR
    (234, 210): 'G',  # LATIN SMALL LIGATURE GP
    (238, 209): 'G',  # LATIN SMALL LIGATURE GG
    (238, 210): 'G',  # LATIN SMALL LIGATURE GD
    (238, 211): 'G',  # LATIN SMALL LIGATURE G D ROTUNDA
    (238, 212): 'G',  # LATIN SMALL LIGATURE G ETH
    (238, 222): 'G',  # LATIN SMALL LIGATURE GO
    (238, 232): 'G',  # LATIN ENLARGED LETTER SMALL G
    (239, 32): 'G',  # LATIN LETTER SMALL CAPITAL G WITH DOT ABOVE
    (239, 39): 'G',  # LATIN LETTER SMALL CAPITAL G WITH DOT BELOW
    (241, 14): 'G',  # LATIN CAPITAL LETTER G SQUARE FORM
    (241, 150): 'G',  # LATIN SMALL LETTER G WITH CURL
    (242, 29): 'G',  # LATIN SMALL LETTER G WITH SEPARATE LOOPS
    (242, 30): 'G',  # LATIN SMALL LETTER CLOSED G WITH LARGE LOWER LOOP
    (242, 31): 'G',  # LATIN SMALL LETTER CLOSED G WITH SMALL LOWER LOOP
    (0, 38): '',  # AMPERSAND
    (0, 46): '',  # FULL STOP
    (0, 59): '',  # SEMICOLON
    (0, 94): '',  # CIRCUMFLEX ACCENT
    (0, 96): '',  # GRAVE ACCENT
    (0, 126): '',  # TILDE
    (0, 168): '',  # DIAERESIS
    (0, 175): '',  # MACRON
    (0, 180): '',  # ACUTE ACCENT
    (0, 184): '',  # CEDILLA
    (2, 188): '',  # MODIFIER LETTER APOSTROPHE
    (2, 200): '',  # MODIFIER LETTER VERTICAL LINE
    (2, 216): '',  # BREVE
    (2, 217): '',  # DOT ABOVE
    (2, 218): '',  # RING ABOVE
    (2, 219): '',  # OGONEK
    (2, 220): '',  # SMALL TILDE
    (2, 221): '',  # DOUBLE ACUTE ACCENT
    (22, 216): '',  # RUNIC MEDIEVAL LETTER M
    (32, 74): '',  # LATIN ABBREVIATION SIGN SMALL ET
    (33, 20): '',  # L B BAR SYMBOL
    (34, 59): '',  # HOMOTHETIC
    (34, 72): '',  # ALMOST EQUAL TO
    (167, 62): '',  # LATIN CAPITAL LETTER REVERSED C WITH DOT
    (167, 63): '',  # LATIN SMALL LETTER REVERSED C WITH DOT
    (167, 74): '',  # LATIN CAPITAL LETTER O WITH LONG STROKE OVERLAY
    (167, 75): '',  # LATIN SMALL LETTER O WITH LONG STROKE OVERLAY
    (167, 92): '',  # LATIN CAPITAL LETTER RUM ROTUNDA
    (167, 93): '',  # LATIN SMALL LETTER RUM ROTUNDA
    (167, 106): '',  # LATIN CAPITAL LETTER ET
    (167, 107): '',  # LATIN SMALL LETTER ET
    (167, 108): '',  # LATIN CAPITAL LETTER IS
    (167, 109): '',  # LATIN SMALL LETTER IS
    (167, 110): '',  # LATIN CAPITAL LETTER CON
    (167, 111): '',  # LATIN SMALL LETTER CON
    (167, 112): '',  # MODIFIER LETTER US
    (167, 120): '',  # LATIN SMALL LETTER UM
    (232, 163): '',  # LATIN ABBREVIATION SIGN AUTEM
    (241, 66): '',  # LATIN ABBREVIATION SIGN CAPITAL ET
    (241, 88): '',  # LATIN ABBREVIATION SIGN SMALL ET WITH STROKE
    (241, 89): '',  # LATIN ABBREVIATION SIGN SMALL DE
    (241, 165): '',  # LATIN ABBREVIATION SIGN SPACING BASE-LINE CAPITAL US
    (241, 166): '',  # LATIN ABBREVIATION SIGN SPACING BASE-LINE US
    (241, 167): '',  # LATIN ABBREVIATION SIGN CAPITAL ET WITH STROKE
    (241, 172): '',  # LATIN ABBREVIATION SIGN SEMICOLON
    (0, 89): 'Y',  # LATIN CAPITAL LETTER Y
    (0, 121): 'Y',  # LATIN SMALL LETTER Y
    (0, 221): 'Y',  # LATIN CAPITAL LETTER Y WITH ACUTE
    (0, 253): 'Y',  # LATIN SMALL LETTER Y WITH ACUTE
    (0, 255): 'Y',  # LATIN SMALL LETTER Y WITH DIAERESIS
    (1, 118): 'Y',  # LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
    (1, 119): 'Y',  # LATIN SMALL LETTER Y WITH CIRCUMFLEX
    (1, 120): 'Y',  # LATIN CAPITAL LETTER Y WITH DIAERESIS
    (2, 50): 'Y',  # LATIN CAPITAL LETTER Y WITH MACRON
    (2, 51): 'Y',  # LATIN SMALL LETTER Y WITH MACRON
    (2, 143): 'Y',  # LATIN LETTER SMALL CAPITAL Y
    (22, 163): 'Y',  # RUNIC LETTER YR
    (22, 164): 'Y',  # RUNIC LETTER Y
    (30, 142): 'Y',  # LATIN CAPITAL LETTER Y WITH DOT ABOVE
    (30, 143): 'Y',  # LATIN SMALL LETTER Y WITH DOT ABOVE
    (30, 153): 'Y',  # LATIN SMALL LETTER Y WITH RING ABOVE
    (30, 242): 'Y',  # LATIN CAPITAL LETTER Y WITH GRAVE
    (30, 243): 'Y',  # LATIN SMALL LETTER Y WITH GRAVE
    (30, 244): 'Y',  # LATIN CAPITAL LETTER Y WITH DOT BELOW
    (30, 245): 'Y',  # LATIN SMALL LETTER Y WITH DOT BELOW
    (30, 246): 'Y',  # LATIN CAPITAL LETTER Y WITH HOOK ABOVE
    (30, 247): 'Y',  # LATIN SMALL LETTER Y WITH HOOK ABOVE
    (30, 254): 'Y',  # LATIN CAPITAL LETTER Y WITH LOOP
    (30, 255): 'Y',  # LATIN SMALL LETTER Y WITH LOOP
    (167, 96): 'Y',  # LATIN CAPITAL LETTER VY
    (167, 97): 'Y',  # LATIN SMALL LETTER VY
    (227, 115): 'Y',  # LATIN CAPITAL LETTER Y WITH MACRON AND ACUTE
    (227, 117): 'Y',  # LATIN CAPITAL LETTER Y WITH MACRON AND BREVE
    (227, 118): 'Y',  # LATIN CAPITAL LETTER Y WITH BREVE
    (227, 124): 'Y',  # LATIN CAPITAL LETTER Y WITH DOUBLE ACUTE
    (227, 132): 'Y',  # LATIN CAPITAL LETTER Y WITH DOT ABOVE AND ACUTE
    (227, 133): 'Y',  # LATIN CAPITAL LETTER Y WITH CURL
    (231, 115): 'Y',  # LATIN SMALL LETTER Y WITH MACRON AND ACUTE
    (231, 117): 'Y',  # LATIN SMALL LETTER Y WITH MACRON AND BREVE
    (231, 118): 'Y',  # LATIN SMALL LETTER Y WITH BREVE
    (231, 123): 'Y',  # LATIN SMALL LETTER Y WITH BAR
    (231, 124): 'Y',  # LATIN SMALL LETTER Y WITH DOUBLE ACUTE
    (231, 129): 'Y',  # LATIN SMALL LETTER Y WITH LATIN SMALL LETTER E ABOVE
    (231, 132): 'Y',  # LATIN SMALL LETTER Y WITH DOT ABOVE AND ACUTE
    (231, 133): 'Y',  # LATIN SMALL LETTER Y WITH CURL
    (235, 202): 'Y',  # LATIN CAPITAL LIGATURE YY WITH DOUBLE ACUTE
    (235, 203): 'Y',  # LATIN SMALL LIGATURE YY WITH DOUBLE ACUTE
    (235, 232): 'Y',  # LATIN CAPITAL LIGATURE YY WITH DIAERESIS
    (235, 233): 'Y',  # LATIN SMALL LIGATURE YY WITH DIAERESIS
    (238, 251): 'Y',  # LATIN ENLARGED LETTER SMALL Y
    (242, 51): 'Y',  # LATIN SMALL LETTER Y WITH RIGHT MAIN STROKE
    (0, 82): 'R',  # LATIN CAPITAL LETTER R
    (0, 114): 'R',  # LATIN SMALL LETTER R
    (1, 84): 'R',  # LATIN CAPITAL LETTER R WITH ACUTE
    (1, 85): 'R',  # LATIN SMALL LETTER R WITH ACUTE
    (1, 166): 'R',  # LATIN LETTER YR
    (2, 124): 'R',  # LATIN SMALL LETTER R WITH LONG LEG
    (2, 128): 'R',  # LATIN LETTER SMALL CAPITAL R
    (30, 88): 'R',  # LATIN CAPITAL LETTER R WITH DOT ABOVE
    (30, 89): 'R',  # LATIN SMALL LETTER R WITH DOT ABOVE
    (30, 90): 'R',  # LATIN CAPITAL LETTER R WITH DOT BELOW
    (30, 91): 'R',  # LATIN SMALL LETTER R WITH DOT BELOW
    (33, 30): 'R',  # PRESCRIPTION TAKE
    (33, 31): 'R',  # RESPONSE
    (167, 90): 'R',  # LATIN CAPITAL LETTER R ROTUNDA
    (167, 91): 'R',  # LATIN SMALL LETTER R ROTUNDA
    (167, 117): 'R',  # LATIN SMALL LETTER RUM
    (167, 118): 'R',  # LATIN LETTER SMALL CAPITAL RUM
    (167, 130): 'R',  # LATIN CAPITAL LETTER INSULAR R
    (167, 131): 'R',  # LATIN SMALL LETTER INSULAR R
    (230, 163): 'R',  # LATIN SMALL LETTER R WITH RING BELOW
    (231, 193): 'R',  # LATIN SMALL LETTER R ROTUNDA WITH DOT BELOW
    (231, 228): 'R',  # LATIN SMALL LETTER R WITH LONG LEG AND STROKE THROUGH DESCENDER
    (232, 234): 'R',  # LATIN SMALL LETTER R WITH LATIN SMALL LETTER E ABOVE
    (235, 185): 'R',  # LATIN SMALL LETTER R ROTUNDA WITH ACUTE
    (238, 243): 'R',  # LATIN ENLARGED LETTER SMALL R
    (239, 34): 'R',  # LATIN LETTER SMALL CAPITAL R WITH DOT ABOVE
    (239, 43): 'R',  # LATIN LETTER SMALL CAPITAL R WITH DOT BELOW
    (241, 155): 'R',  # LATIN SMALL LETTER R WITH FLOURISH
    (0, 88): 'X',  # LATIN CAPITAL LETTER X
    (0, 120): 'X',  # LATIN SMALL LETTER X
    (2, 227): 'X',  # MODIFIER LETTER SMALL X
    (171, 87): 'X',  # LATIN SMALL LETTER X WITH LONG LEFT LEG
    (232, 189): 'X',  # LATIN SMALL LETTER X WITH SHORT SLASH ABOVE
    (232, 190): 'X',  # LATIN SMALL LETTER X WITH SHORT SLASH BELOW
    (232, 206): 'X',  # LATIN SMALL LETTER X WITH TWO SHORT SLASHES BELOW RIGHT
    (238, 250): 'X',  # LATIN ENLARGED LETTER SMALL X
    (239, 17): 'X',  # LATIN LETTER SMALL CAPITAL X
    (242, 50): 'X',  # LATIN SMALL LETTER X WITH LEFT DESCENDER
    (247, 179): 'X',  # LATIN CAPITAL LETTER X WITH HIGH OVERLINE (ABOVE CHARACTER)
    (0, 74): 'J',  # LATIN CAPITAL LETTER J
    (0, 106): 'J',  # LATIN SMALL LETTER J
    (2, 55): 'J',  # LATIN SMALL LETTER DOTLESS J
    (2, 72): 'J',  # LATIN CAPITAL LETTER J WITH STROKE
    (2, 73): 'J',  # LATIN SMALL LETTER J WITH STROKE
    (2, 95): 'J',  # LATIN SMALL LETTER DOTLESS J WITH STROKE
    (29, 10): 'J',  # LATIN LETTER SMALL CAPITAL J
    (225, 81): 'J',  # LATIN CAPITAL LETTER J WITH DOT BELOW
    (225, 82): 'J',  # LATIN CAPITAL LETTER J WITH HIGH OVERLINE (ABOVE CHARACTER)
    (225, 83): 'J',  # LATIN CAPITAL LETTER J WITH ACUTE
    (225, 84): 'J',  # LATIN CAPITAL LETTER J WITH HIGH MACRON (ABOVE CHARACTER)
    (225, 92): 'J',  # LATIN CAPITAL LETTER J WITH DOT ABOVE
    (225, 98): 'J',  # LATIN CAPITAL LETTER J WITH DOUBLE ACUTE
    (225, 99): 'J',  # LATIN CAPITAL LETTER J WITH CURL
    (229, 81): 'J',  # LATIN SMALL LETTER J WITH DOT BELOW
    (229, 82): 'J',  # LATIN SMALL LETTER J WITH MEDIUM-HIGH OVERLINE (ABOVE CHARACTER)
    (229, 83): 'J',  # LATIN SMALL LETTER J WITH ACUTE
    (229, 84): 'J',  # LATIN SMALL LETTER J WITH MEDIUM-HIGH MACRON (ABOVE CHARACTER)
    (229, 98): 'J',  # LATIN SMALL LETTER J WITH DOUBLE ACUTE
    (229, 99): 'J',  # LATIN SMALL LETTER J WITH CURL
    (232, 162): 'J',  # LATIN SMALL LETTER J WITH TWO STROKES
    (232, 231): 'J',  # LATIN SMALL LETTER J WITH LATIN SMALL LETTER E ABOVE
    (235, 226): 'J',  # LATIN CAPITAL LETTER J WITH DIAERESIS
    (235, 227): 'J',  # LATIN SMALL LETTER J WITH DIAERESIS
    (238, 235): 'J',  # LATIN ENLARGED LETTER SMALL J
    (238, 254): 'J',  # LATIN ENLARGED LETTER SMALL DOTLESS J
    (0, 80): 'P',  # LATIN CAPITAL LETTER P
    (0, 112): 'P',  # LATIN SMALL LETTER P
    (29, 24): 'P',  # LATIN LETTER SMALL CAPITAL P
    (30, 84): 'P',  # LATIN CAPITAL LETTER P WITH ACUTE
    (30, 85): 'P',  # LATIN SMALL LETTER P WITH ACUTE
    (30, 86): 'P',  # LATIN CAPITAL LETTER P WITH DOT ABOVE
    (30, 87): 'P',  # LATIN SMALL LETTER P WITH DOT ABOVE
    (167, 80): 'P',  # LATIN CAPITAL LETTER P WITH STROKE THROUGH DESCENDER
    (167, 81): 'P',  # LATIN SMALL LETTER P WITH STROKE THROUGH DESCENDER
    (167, 82): 'P',  # LATIN CAPITAL LETTER P WITH FLOURISH
    (167, 83): 'P',  # LATIN SMALL LETTER P WITH FLOURISH
    (167, 84): 'P',  # LATIN CAPITAL LETTER P WITH SQUIRREL TAIL
    (167, 85): 'P',  # LATIN SMALL LETTER P WITH SQUIRREL TAIL
    (167, 252): 'P',  # LATIN EPIGRAPHIC LETTER REVERSED P
    (226, 104): 'P',  # LATIN CAPITAL LETTER P WITH DOUBLE ACUTE
    (226, 109): 'P',  # LATIN CAPITAL LETTER P WITH DOT BELOW
    (230, 101): 'P',  # LATIN SMALL LETTER P WITH MACRON
    (230, 104): 'P',  # LATIN SMALL LETTER P WITH DOUBLE ACUTE
    (230, 109): 'P',  # LATIN SMALL LETTER P WITH DOT BELOW
    (235, 207): 'P',  # LATIN LETTER SMALL CAPITAL P WITH DOT ABOVE
    (235, 230): 'P',  # LATIN CAPITAL LIGATURE PP WITH DIAERESIS
    (235, 231): 'P',  # LATIN SMALL LIGATURE PP WITH DIAERESIS
    (238, 214): 'P',  # LATIN SMALL LIGATURE PP
    (238, 215): 'P',  # LATIN SMALL LIGATURE PP WITH FLOURISH
    (238, 221): 'P',  # LATIN CAPITAL LIGATURE PP
    (238, 241): 'P',  # LATIN ENLARGED LETTER SMALL P
    (0, 78): 'N',  # LATIN CAPITAL LETTER N
    (0, 110): 'N',  # LATIN SMALL LETTER N
    (0, 209): 'N',  # LATIN CAPITAL LETTER N WITH TILDE
    (0, 241): 'N',  # LATIN SMALL LETTER N WITH TILDE
    (1, 67): 'N',  # LATIN CAPITAL LETTER N WITH ACUTE
    (1, 68): 'N',  # LATIN SMALL LETTER N WITH ACUTE
    (1, 74): 'N',  # LATIN CAPITAL LETTER ENG
    (1, 75): 'N',  # LATIN SMALL LETTER ENG
    (1, 158): 'N',  # LATIN SMALL LETTER N WITH LONG RIGHT LEG
    (2, 114): 'N',  # LATIN SMALL LETTER N WITH LEFT HOOK
    (2, 116): 'N',  # LATIN LETTER SMALL CAPITAL N
    (30, 68): 'N',  # LATIN CAPITAL LETTER N WITH DOT ABOVE
    (30, 69): 'N',  # LATIN SMALL LETTER N WITH DOT ABOVE
    (30, 70): 'N',  # LATIN CAPITAL LETTER N WITH DOT BELOW
    (30, 71): 'N',  # LATIN SMALL LETTER N WITH DOT BELOW
    (167, 116): 'N',  # LATIN SMALL LETTER NUM
    (225, 220): 'N',  # LATIN CAPITAL LETTER N WITH HIGH MACRON (ABOVE CHARACTER)
    (229, 215): 'N',  # LATIN SMALL LETTER N WITH CIRCUMFLEX
    (229, 220): 'N',  # LATIN SMALL LETTER N WITH MEDIUM-HIGH MACRON (ABOVE CHARACTER)
    (229, 238): 'N',  # LATIN SMALL LETTER N WITH RING BELOW
    (231, 178): 'N',  # LATIN SMALL LETTER N WITH BAR
    (238, 213): 'N',  # LATIN SMALL LIGATURE SMALL CAPITAL N LONG S
    (238, 239): 'N',  # LATIN ENLARGED LETTER SMALL N
    (239, 33): 'N',  # LATIN LETTER SMALL CAPITAL N WITH DOT ABOVE
    (239, 42): 'N',  # LATIN LETTER SMALL CAPITAL N WITH DOT BELOW
    (241, 154): 'N',  # LATIN SMALL LETTER N WITH FLOURISH
    (242, 40): 'N',  # LATIN SMALL LETTER N WITH RIGHT DESCENDER
    (242, 41): 'N',  # LATIN CAPITAL LETTER N WITH RIGHT DESCENDER
    (242, 42): 'N',  # LATIN LETTER SMALL CAPITAL N WITH RIGHT DESCENDER
    (242, 43): 'N',  # LATIN LETTER SMALL CAPITAL N WITH LEFT DESCENDER
    (0, 35): '',  # NUMBER SIGN
    (0, 36): '',  # DOLLAR SIGN
    (0, 37): '',  # PERCENT SIGN
    (0, 42): '',  # ASTERISK
    (0, 43): '',  # PLUS SIGN
    (0, 61): '',  # EQUALS SIGN
    (0, 64): '',  # COMMERCIAL AT
    (0, 162): '',  # CENT SIGN
    (0, 163): '',  # POUND SIGN
    (0, 164): '',  # CURRENCY SIGN
    (0, 165): '',  # YEN SIGN
    (0, 167): '',  # SECTION SIGN
    (0, 169): '',  # COPYRIGHT SIGN
    (0, 172): '',  # NOT SIGN
    (0, 174): '',  # REGISTERED SIGN
    (0, 176): '',  # DEGREE SIGN
    (0, 177): '',  # PLUS-MINUS SIGN
    (0, 181): '',  # MICRO SIGN
    (0, 182): '',  # PILCROW SIGN
    (0, 215): '',  # MULTIPLICATION SIGN
    (0, 247): '',  # DIVISION SIGN
    (32, 32): '',  # DAGGER
    (32, 33): '',  # DOUBLE DAGGER
    (32, 48): '',  # PER MILLE SIGN
    (32, 59): '',  # REFERENCE MARK
    (32, 66): '',  # ASTERISM
    (32, 75): '',  # REVERSED PILCROW SIGN
    (32, 92): '',  # DOTTED CROSS
    (32, 176): '',  # GERMAN PENNY SIGN
    (33, 8): '',  # SCRUPLE
    (33, 37): '',  # OUNCE SIGN
    (34, 18): '',  # MINUS
    (34, 30): '',  # INFINITY
    (34, 39): '',  # LOGICAL AND
    (34, 96): '',  # NOT EQUAL TO
    (39, 29): '',  # LATIN CROSS
    (39, 102): '',  # FLORAL HEART
    (39, 103): '',  # ROTATED FLORAL HEART BULLET
    (241, 189): '',  # SMALL BASE LINE ZERO SIGN
    (241, 210): '',  # TRIPLE DAGGER
    (242, 224): '',  # LATIN AS LIBRALIS SIGN
    (242, 226): '',  # LATIN SMALL CAPITAL LETTER X WITH BAR
    (242, 227): '',  # LATIN SMALL CAPITAL LETTER Y WITH BAR
    (242, 228): '',  # LATIN SMALL CAPITAL LETTER D WITH SLASH
    (242, 230): '',  # PHARMACEUTICAL DRAM SIGN
    (242, 231): '',  # ECU SIGN
    (242, 232): '',  # FLOREN SIGN WITH LOOP
    (242, 233): '',  # GROSCHEN SIGN
    (242, 234): '',  # DUTCH LIBRA SIGN
    (242, 235): '',  # FRENCH LIBRA SIGN
    (242, 236): '',  # ITALIAN LIBRA SIGN
    (242, 237): '',  # FLEMISH LIBRA SIGN
    (242, 238): '',  # LIRA NUOVA SIGN
    (242, 239): '',  # LIRA STERLINA SIGN
    (242, 240): '',  # OLD MARK SIGN
    (242, 241): '',  # OLD FLOURISH MARK SIGN
    (242, 242): '',  # MARKED SMALL LETTER M SIGN
    (242, 243): '',  # FLOURISHED SMALL LETTER M SIGN
    (242, 244): '',  # PHARMACEUTICAL OBOLUS SIGN
    (242, 245): '',  # PENNING SIGN
    (242, 246): '',  # OLD REICHSTALER SIGN
    (242, 247): '',  # GERMAN SCHILLING SIGN
    (242, 248): '',  # GERMAN SCRIPT SCHILLING SIGN
    (242, 249): '',  # SCUDI SIGN
    (242, 250): '',  # KRONE SIGN
    (242, 251): '',  # HELBING SIGN
    (242, 253): '',  # SCRIPT OUNCE SIGN
    (257, 144): '',  # ROMAN SEXTANS SIGN
    (257, 145): '',  # ROMAN UNCIA SIGN
    (257, 146): '',  # ROMAN SEMIUNCIA SIGN
    (257, 147): '',  # ROMAN SEXTULA SIGN
    (257, 148): '',  # ROMAN DIMIDIA SEXTULA SIGN
    (257, 149): '',  # ROMAN SILIQUA SIGN
    (257, 150): '',  # LATIN CAPITAL LETTER X WITH BAR
    (257, 151): '',  # ROMAN QUINARIUS SIGN
    (257, 152): '',  # SESTERTIA SIGN
    (257, 153): '',  # ROMAN DUPONDIUS SIGN
    (257, 154): '',  # ROMAN AS SIGN
    (0, 48): '',  # DIGIT ZERO
    (0, 49): '',  # DIGIT ONE
    (0, 50): '',  # DIGIT TWO
    (0, 51): '',  # DIGIT THREE
    (0, 52): '',  # DIGIT FOUR
    (0, 53): '',  # DIGIT FIVE
    (0, 54): '',  # DIGIT SIX
    (0, 55): '',  # DIGIT SEVEN
    (0, 56): '',  # DIGIT EIGHT
    (0, 57): '',  # DIGIT NINE
    (0, 178): '',  # SUPERSCRIPT TWO
    (0, 179): '',  # SUPERSCRIPT THREE
    (0, 185): '',  # SUPERSCRIPT ONE
    (0, 188): '',  # VULGAR FRACTION ONE QUARTER
    (0, 189): '',  # VULGAR FRACTION ONE HALF
    (0, 190): '',  # VULGAR FRACTION THREE QUARTERS
    (29, 53): '',  # MODIFIER CAPITAL LETTER I
    (32, 112): '',  # SUPERSCRIPT ZERO
    (32, 116): '',  # SUPERSCRIPT FOUR
    (32, 117): '',  # SUPERSCRIPT FIVE
    (32, 118): '',  # SUPERSCRIPT SIX
    (32, 119): '',  # SUPERSCRIPT SEVEN
    (32, 120): '',  # SUPERSCRIPT EIGHT
    (32, 121): '',  # SUPERSCRIPT NINE
    (32, 128): '',  # SUBSCRIPT ZERO
    (32, 129): '',  # SUBSCRIPT ONE
    (32, 130): '',  # SUBSCRIPT TWO
    (32, 131): '',  # SUBSCRIPT THREE
    (32, 132): '',  # SUBSCRIPT FOUR
    (32, 133): '',  # SUBSCRIPT FIVE
    (32, 134): '',  # SUBSCRIPT SIX
    (32, 135): '',  # SUBSCRIPT SEVEN
    (32, 136): '',  # SUBSCRIPT EIGHT
    (32, 137): '',  # SUBSCRIPT NINE
    (33, 128): '',  # ROMAN NUMERAL ONE THOUSAND C D
    (33, 129): '',  # ROMAN NUMERAL FIVE THOUSAND
    (33, 130): '',  # ROMAN NUMERAL TEN THOUSAND
    (33, 131): '',  # ROMAN NUMERAL REVERSED ONE HUNDRED
    (241, 190): '',  # MODIFIER CAPITAL LETTER V
    (241, 191): '',  # MODIFIER CAPITAL LETTER X
    (242, 63): '',  # ROMAN NUMERAL REVERSED ONE HUNDRED WITH OVERLINE
    (0, 72): 'H',  # LATIN CAPITAL LETTER H
    (0, 104): 'H',  # LATIN SMALL LETTER H
    (1, 39): 'H',  # LATIN SMALL LETTER H WITH STROKE
    (1, 149): 'H',  # LATIN SMALL LETTER HV
    (1, 246): 'H',  # LATIN CAPITAL LETTER HWAIR
    (2, 102): 'H',  # LATIN SMALL LETTER H WITH HOOK
    (2, 156): 'H',  # LATIN LETTER SMALL CAPITAL H
    (30, 34): 'H',  # LATIN SMALL LETTER H WITH DOT ABOVE
    (30, 35): 'H',  # LATIN CAPITAL LETTER H WITH DOT ABOVE
    (30, 36): 'H',  # LATIN CAPITAL LETTER H WITH DOT BELOW
    (30, 37): 'H',  # LATIN SMALL LETTER H WITH DOT BELOW
    (44, 117): 'H',  # LATIN CAPITAL LETTER HALF H
    (44, 118): 'H',  # LATIN SMALL LETTER HALF H
    (225, 22): 'H',  # LATIN CAPITAL LETTER H WITH ACUTE
    (229, 22): 'H',  # LATIN SMALL LETTER H WITH ACUTE
    (229, 23): 'H',  # LATIN SMALL LETTER H WITH MEDIUM-HIGH OVERLINE (ACROSS ASCENDER)
    (231, 199): 'H',  # LATIN SMALL LIGATURE H AND LONG S WITH STROKE
    (232, 194): 'H',  # LATIN CAPITAL LETTER H LIGATED WITH ARM OF LATIN SMALL LETTER R
    (232, 195): 'H',  # LATIN SMALL LETTER H LIGATED WITH ARM OF LATIN SMALL LETTER R
    (235, 173): 'H',  # LATIN SMALL LIGATURE H AND LONG S
    (235, 218): 'H',  # LATIN LETTER SMALL CAPITAL H WITH DOT ABOVE
    (238, 233): 'H',  # LATIN ENLARGED LETTER SMALL H
    (241, 16): 'H',  # LATIN CAPITAL LETTER UNCIAL H
    (242, 58): 'H',  # LATIN SMALL LETTER H WITH RIGHT DESCENDER
    (0, 76): 'L',  # LATIN CAPITAL LETTER L
    (0, 108): 'L',  # LATIN SMALL LETTER L
    (1, 57): 'L',  # LATIN CAPITAL LETTER L WITH ACUTE
    (1, 58): 'L',  # LATIN SMALL LETTER L WITH ACUTE
    (1, 65): 'L',  # LATIN CAPITAL LETTER L WITH STROKE
    (1, 66): 'L',  # LATIN SMALL LETTER L WITH STROKE
    (1, 154): 'L',  # LATIN SMALL LETTER L WITH BAR
    (2, 159): 'L',  # LATIN LETTER SMALL CAPITAL L
    (30, 54): 'L',  # LATIN CAPITAL LETTER L WITH DOT BELOW
    (30, 55): 'L',  # LATIN SMALL LETTER L WITH DOT BELOW
    (30, 250): 'L',  # LATIN CAPITAL LETTER MIDDLE-WELSH LL
    (30, 251): 'L',  # LATIN SMALL LETTER MIDDLE-WELSH LL
    (167, 70): 'L',  # LATIN CAPITAL LETTER BROKEN L
    (167, 71): 'L',  # LATIN SMALL LETTER BROKEN L
    (167, 72): 'L',  # LATIN CAPITAL LETTER L WITH HIGH STROKE
    (167, 73): 'L',  # LATIN SMALL LETTER L WITH HIGH STROKE
    (167, 114): 'L',  # LATIN SMALL LETTER LUM
    (167, 128): 'L',  # LATIN CAPITAL LETTER TURNED L
    (167, 129): 'L',  # LATIN SMALL LETTER TURNED L
    (225, 158): 'L',  # LATIN CAPITAL LETTER L WITH DOT ABOVE
    (229, 140): 'L',  # LATIN SMALL LETTER L WITH HIGH OVERLINE (ABOVE CHARACTER)
    (229, 150): 'L',  # LATIN SMALL LETTER L WITH HIGH MACRON (ABOVE CHARACTER)
    (229, 158): 'L',  # LATIN SMALL LETTER L WITH DOT ABOVE
    (229, 164): 'L',  # LATIN SMALL LETTER L WITH RING BELOW
    (229, 177): 'L',  # LATIN SMALL LETTER L WITH MEDIUM-HIGH OVERLINE (ACROSS ASCENDER)
    (235, 220): 'L',  # LATIN LETTER SMALL CAPITAL L WITH DOT ABOVE
    (238, 237): 'L',  # LATIN ENLARGED LETTER SMALL L
    (239, 40): 'L',  # LATIN LETTER SMALL CAPITAL L WITH DOT BELOW
    (242, 34): 'L',  # LATIN SMALL LETTER L DESCENDING
    (244, 249): 'L',  # LATIN SMALL LIGATURE LL
    (247, 180): 'L',  # LATIN CAPITAL LETTER L WITH HIGH OVERLINE (ABOVE CHARACTER)
    (0, 70): 'F',  # LATIN CAPITAL LETTER F
    (0, 102): 'F',  # LATIN SMALL LETTER F
    (22, 160): 'F',  # RUNIC LETTER FEHU FEOH FE F
    (30, 30): 'F',  # LATIN CAPITAL LETTER F WITH DOT ABOVE
    (30, 31): 'F',  # LATIN SMALL LETTER F WITH DOT ABOVE
    (33, 50): 'F',  # TURNED CAPITAL F
    (33, 78): 'F',  # TURNED SMALL F
    (167, 48): 'F',  # LATIN LETTER SMALL CAPITAL F
    (167, 123): 'F',  # LATIN CAPITAL LETTER INSULAR F
    (167, 124): 'F',  # LATIN SMALL LETTER INSULAR F
    (167, 251): 'F',  # LATIN EPIGRAPHIC LETTER REVERSED F
    (224, 238): 'F',  # LATIN CAPITAL LETTER F WITH DOT BELOW
    (224, 240): 'F',  # LATIN CAPITAL LETTER F WITH ACUTE
    (227, 229): 'F',  # LATIN CAPITAL LETTER INSULAR F WITH DOT BELOW
    (228, 238): 'F',  # LATIN SMALL LETTER F WITH DOT BELOW
    (228, 240): 'F',  # LATIN SMALL LETTER F WITH ACUTE
    (231, 229): 'F',  # LATIN SMALL LETTER INSULAR F WITH DOT BELOW
    (235, 179): 'F',  # LATIN CAPITAL LETTER INSULAR F WITH ACUTE
    (235, 180): 'F',  # LATIN SMALL LETTER INSULAR F WITH ACUTE
    (235, 211): 'F',  # LATIN CAPITAL LETTER INSULAR F WITH DOT ABOVE
    (235, 212): 'F',  # LATIN SMALL LETTER INSULAR F WITH DOT ABOVE
    (235, 213): 'F',  # LATIN SMALL LETTER SEMI-CLOSED INSULAR F WITH DOT ABOVE
    (235, 214): 'F',  # LATIN SMALL LETTER CLOSED INSULAR F WITH DOT ABOVE
    (235, 215): 'F',  # LATIN LETTER SMALL CAPITAL F WITH DOT ABOVE
    (238, 200): 'F',  # LATIN SMALL LIGATURE F A WITH DIAERESIS
    (238, 201): 'F',  # LATIN SMALL LIGATURE FJ
    (238, 202): 'F',  # LATIN SMALL LIGATURE FR
    (238, 203): 'F',  # LATIN SMALL LIGATURE FT
    (238, 204): 'F',  # LATIN SMALL LIGATURE F U WITH DIAERESIS
    (238, 205): 'F',  # LATIN SMALL LIGATURE FY
    (238, 206): 'F',  # LATIN SMALL LIGATURE FFT
    (238, 207): 'F',  # LATIN SMALL LIGATURE FFY
    (238, 208): 'F',  # LATIN SMALL LIGATURE FTY
    (238, 231): 'F',  # LATIN ENLARGED LETTER SMALL F
    (238, 255): 'F',  # LATIN ENLARGED LETTER SMALL INSULAR F
    (241, 148): 'F',  # LATIN SMALL LETTER F WITH CURL
    (241, 188): 'F',  # LATIN SMALL LIGATURE F O WITH DIAERESIS
    (242, 7): 'F',  # LATIN SMALL LETTER CLOSED INSULAR F
    (242, 27): 'F',  # LATIN SMALL LETTER SEMI-CLOSED INSULAR F
    (242, 28): 'F',  # LATIN SMALL LETTER INSULAR F WITH DOTTED HOOKS
    (251, 0): 'F',  # LATIN SMALL LIGATURE FF
    (251, 1): 'F',  # LATIN SMALL LIGATURE FI
    (251, 2): 'F',  # LATIN SMALL LIGATURE FL
    (251, 3): 'F',  # LATIN SMALL LIGATURE FFI
    (251, 4): 'F',  # LATIN SMALL LIGATURE FFL
    (0, 77): 'M',  # LATIN CAPITAL LETTER M
    (0, 109): 'M',  # LATIN SMALL LETTER M
    (1, 156): 'M',  # LATIN CAPITAL LETTER TURNED M
    (2, 111): 'M',  # LATIN SMALL LETTER TURNED M
    (29, 13): 'M',  # LATIN LETTER SMALL CAPITAL M
    (30, 62): 'M',  # LATIN CAPITAL LETTER M WITH ACUTE
    (30, 63): 'M',  # LATIN SMALL LETTER M WITH ACUTE
    (30, 64): 'M',  # LATIN CAPITAL LETTER M WITH DOT ABOVE
    (30, 65): 'M',  # LATIN SMALL LETTER M WITH DOT ABOVE
    (30, 66): 'M',  # LATIN CAPITAL LETTER M WITH DOT BELOW
    (30, 67): 'M',  # LATIN SMALL LETTER M WITH DOT BELOW
    (167, 115): 'M',  # LATIN SMALL LETTER MUM
    (167, 253): 'M',  # LATIN EPIGRAPHIC LETTER INVERTED M
    (167, 255): 'M',  # LATIN EPIGRAPHIC LETTER ARCHAIC M
    (225, 184): 'M',  # LATIN CAPITAL LETTER M WITH HIGH MACRON (ABOVE CHARACTER)
    (225, 210): 'M',  # LATIN CAPITAL LETTER M WITH HIGH OVERLINE (ABOVE CHARACTER)
    (229, 184): 'M',  # LATIN SMALL LETTER M WITH MEDIUM-HIGH MACRON (ABOVE CHARACTER)
    (229, 197): 'M',  # LATIN SMALL LETTER M WITH RING BELOW
    (229, 210): 'M',  # LATIN SMALL LETTER M WITH MEDIUM-HIGH OVERLINE (ABOVE CHARACTER)
    (232, 232): 'M',  # LATIN SMALL LETTER M WITH LATIN SMALL LETTER E ABOVE
    (235, 181): 'M',  # LATIN CAPITAL LETTER UNCIAL M WITH ACUTE
    (235, 182): 'M',  # LATIN SMALL LETTER UNCIAL M WITH ACUTE
    (235, 221): 'M',  # LATIN LETTER SMALL CAPITAL M WITH DOT ABOVE
    (238, 238): 'M',  # LATIN ENLARGED LETTER SMALL M
    (239, 41): 'M',  # LATIN LETTER SMALL CAPITAL M WITH DOT BELOW
    (241, 26): 'M',  # LATIN CAPITAL LETTER UNCIAL M
    (242, 35): 'M',  # LATIN SMALL LETTER M WITH RIGHT DESCENDER
    (242, 36): 'M',  # LATIN CAPITAL LETTER UNCIAL M WITH RIGHT DESCENDER
    (242, 37): 'M',  # LATIN MEDIUSCULE LETTER M UNCIAL FORM
    (242, 38): 'M',  # LATIN SMALL LETTER UNCIAL M WITH RIGH DESCENDER
    (242, 60): 'M',  # LATIN SMALL LETTER M UNCIAL FORM
    (242, 61): 'M',  # LATIN SMALL LETTER M UNCIAL FORM WITH RIGHT DESCENDER
    (242, 62): 'M',  # LATIN SMALL LETTER M UNCIAL FORM WITH ACUTE ACCENT
    (0, 84): 'T',  # LATIN CAPITAL LETTER T
    (0, 116): 'T',  # LATIN SMALL LETTER T
    (3, 152): 'T',  # GREEK CAPITAL LETTER THETA
    (3, 184): 'T',  # GREEK SMALL LETTER THETA
    (29, 27): 'T',  # LATIN LETTER SMALL CAPITAL T
    (30, 106): 'T',  # LATIN CAPITAL LETTER T WITH DOT ABOVE
    (30, 107): 'T',  # LATIN SMALL LETTER T WITH DOT ABOVE
    (30, 108): 'T',  # LATIN CAPITAL LETTER T WITH DOT BELOW
    (30, 109): 'T',  # LATIN SMALL LETTER T WITH DOT BELOW
    (167, 119): 'T',  # LATIN SMALL LETTER TUM
    (167, 134): 'T',  # LATIN CAPITAL LETTER INSULAR T
    (167, 135): 'T',  # LATIN SMALL LETTER INSULAR T
    (226, 226): 'T',  # LATIN CAPITAL LETTER T WITH ACUTE
    (226, 238): 'T',  # LATIN CAPITAL LETTER T WITH OGONEK
    (230, 226): 'T',  # LATIN SMALL LETTER T WITH ACUTE
    (230, 238): 'T',  # LATIN SMALL LETTER T WITH OGONEK
    (238, 216): 'T',  # LATIN SMALL LIGATURE TR
    (238, 217): 'T',  # LATIN SMALL LIGATURE TT
    (238, 218): 'T',  # LATIN SMALL LIGATURE T ROTUNDA T ROTUNDA
    (238, 219): 'T',  # LATIN SMALL LIGATURE TY
    (238, 220): 'T',  # LATIN SMALL LIGATURE TZ
    (238, 245): 'T',  # LATIN ENLARGED LETTER SMALL T
    (239, 36): 'T',  # LATIN LETTER SMALL CAPITAL T WITH DOT ABOVE
    (239, 45): 'T',  # LATIN LETTER SMALL CAPITAL T WITH DOT BELOW
    (241, 153): 'T',  # LATIN SMALL LETTER T WITH CURL
    (0, 73): 'I',  # LATIN CAPITAL LETTER I
    (0, 105): 'I',  # LATIN SMALL LETTER I
    (0, 204): 'I',  # LATIN CAPITAL LETTER I WITH GRAVE
    (0, 205): 'I',  # LATIN CAPITAL LETTER I WITH ACUTE
    (0, 206): 'I',  # LATIN CAPITAL LETTER I WITH CIRCUMFLEX
    (0, 207): 'I',  # LATIN CAPITAL LETTER I WITH DIAERESIS
    (0, 236): 'I',  # LATIN SMALL LETTER I WITH GRAVE
    (0, 237): 'I',  # LATIN SMALL LETTER I WITH ACUTE
    (0, 238): 'I',  # LATIN SMALL LETTER I WITH CIRCUMFLEX
    (0, 239): 'I',  # LATIN SMALL LETTER I WITH DIAERESIS
    (1, 42): 'I',  # LATIN CAPITAL LETTER I WITH MACRON
    (1, 43): 'I',  # LATIN SMALL LETTER I WITH MACRON
    (1, 44): 'I',  # LATIN CAPITAL LETTER I WITH BREVE
    (1, 45): 'I',  # LATIN SMALL LETTER I WITH BREVE
    (1, 46): 'I',  # LATIN CAPITAL LETTER I WITH OGONEK
    (1, 47): 'I',  # LATIN SMALL LETTER I WITH OGONEK
    (1, 48): 'I',  # LATIN CAPITAL LETTER I WITH DOT ABOVE
    (1, 49): 'I',  # LATIN SMALL LETTER DOTLESS I
    (1, 50): 'I',  # LATIN CAPITAL LIGATURE IJ
    (1, 51): 'I',  # LATIN SMALL LIGATURE IJ
    (2, 104): 'I',  # LATIN SMALL LETTER I WITH STROKE
    (2, 106): 'I',  # LATIN LETTER SMALL CAPITAL I
    (30, 200): 'I',  # LATIN CAPITAL LETTER I WITH HOOK ABOVE
    (30, 201): 'I',  # LATIN SMALL LETTER I WITH HOOK ABOVE
    (30, 202): 'I',  # LATIN CAPITAL LETTER I WITH DOT BELOW
    (30, 203): 'I',  # LATIN SMALL LETTER I WITH DOT BELOW
    (167, 254): 'I',  # LATIN EPIGRAPHIC LETTER I LONGA
    (225, 42): 'I',  # LATIN CAPITAL LETTER I WITH CURL
    (225, 53): 'I',  # LATIN CAPITAL LETTER I WITH MACRON AND ACUTE
    (225, 55): 'I',  # LATIN CAPITAL LETTER I WITH MACRON AND BREVE
    (225, 67): 'I',  # LATIN CAPITAL LETTER I WITH DOUBLE ACUTE
    (225, 80): 'I',  # LATIN CAPITAL LETTER I WITH HIGH OVERLINE (ABOVE CHARACTER)
    (229, 42): 'I',  # LATIN SMALL LETTER I WITH CURL
    (229, 53): 'I',  # LATIN SMALL LETTER I WITH MACRON AND ACUTE
    (229, 55): 'I',  # LATIN SMALL LETTER I WITH MACRON AND BREVE
    (229, 67): 'I',  # LATIN SMALL LETTER I WITH DOUBLE ACUTE
    (229, 72): 'I',  # LATIN SMALL LETTER I WITH INVERTED BREVE BELOW
    (229, 74): 'I',  # LATIN SMALL LETTER I WITH LATIN SMALL LETTER E ABOVE
    (229, 75): 'I',  # LATIN SMALL LETTER I WITH LATIN SMALL LETTER V ABOVE
    (229, 80): 'I',  # LATIN SMALL LETTER I WITH MEDIUM-HIGH OVERLINE (ABOVE CHARACTER)
    (232, 161): 'I',  # LATIN SMALL LETTER I WITH TWO STROKES
    (232, 221): 'I',  # LATIN SMALL LETTER DOTLESS I WITH OGONEK
    (232, 228): 'I',  # LATIN SMALL LETTER I WITH LATIN SMALL LETTER A ABOVE
    (232, 229): 'I',  # LATIN SMALL LETTER I WITH LATIN SMALL LETTER O ABOVE
    (232, 230): 'I',  # LATIN SMALL LETTER I WITH LATIN SMALL LETTER U ABOVE
    (235, 246): 'I',  # LATIN CAPITAL LETTER I WITH DOT ABOVE AND ACUTE
    (235, 247): 'I',  # LATIN SMALL LETTER I WITH DOT ABOVE AND ACUTE
    (238, 234): 'I',  # LATIN ENLARGED LETTER SMALL I
    (238, 253): 'I',  # LATIN ENLARGED LETTER SMALL DOTLESS I
    (242, 32): 'I',  # LATIN SMALL LETTER LONG I
    (0, 87): 'W',  # LATIN CAPITAL LETTER W
    (0, 119): 'W',  # LATIN SMALL LETTER W
    (1, 116): 'W',  # LATIN CAPITAL LETTER W WITH CIRCUMFLEX
    (1, 117): 'W',  # LATIN SMALL LETTER W WITH CIRCUMFLEX
    (22, 165): 'W',  # RUNIC LETTER W
    (29, 33): 'W',  # LATIN LETTER SMALL CAPITAL W
    (30, 128): 'W',  # LATIN CAPITAL LETTER W WITH GRAVE
    (30, 129): 'W',  # LATIN SMALL LETTER W WITH GRAVE
    (30, 130): 'W',  # LATIN CAPITAL LETTER W WITH ACUTE
    (30, 131): 'W',  # LATIN SMALL LETTER W WITH ACUTE
    (30, 132): 'W',  # LATIN CAPITAL LETTER W WITH DIAERESIS
    (30, 133): 'W',  # LATIN SMALL LETTER W WITH DIAERESIS
    (30, 134): 'W',  # LATIN CAPITAL LETTER W WITH DOT ABOVE
    (30, 135): 'W',  # LATIN SMALL LETTER W WITH DOT ABOVE
    (30, 136): 'W',  # LATIN CAPITAL LETTER W WITH DOT BELOW
    (30, 137): 'W',  # LATIN SMALL LETTER W WITH DOT BELOW
    (30, 152): 'W',  # LATIN SMALL LETTER W WITH RING ABOVE
    (227, 80): 'W',  # LATIN CAPITAL LETTER W WITH DOUBLE ACUTE
    (227, 83): 'W',  # LATIN CAPITAL LETTER W WITH LATIN SMALL LETTER E ABOVE
    (227, 87): 'W',  # LATIN CAPITAL LETTER W WITH MACRON
    (231, 80): 'W',  # LATIN SMALL LETTER W WITH DOUBLE ACUTE
    (231, 83): 'W',  # LATIN SMALL LETTER W WITH LATIN SMALL LETTER E ABOVE
    (231, 84): 'W',  # LATIN SMALL LETTER W WITH LATIN SMALL LETTER O ABOVE
    (231, 87): 'W',  # LATIN SMALL LETTER W WITH MACRON
    (232, 240): 'W',  # LATIN SMALL LETTER W WITH LATIN SMALL LETTER A ABOVE
    (232, 241): 'W',  # LATIN SMALL LETTER W WITH LATIN SMALL LETTER I ABOVE
    (232, 242): 'W',  # LATIN SMALL LETTER W WITH LATIN SMALL LETTER U ABOVE
    (232, 243): 'W',  # LATIN SMALL LETTER W WITH LATIN SMALL LETTER V ABOVE
    (238, 249): 'W',  # LATIN ENLARGED LETTER SMALL W
    (0, 81): 'Q',  # LATIN CAPITAL LETTER Q
    (0, 113): 'Q',  # LATIN SMALL LETTER Q
    (167, 86): 'Q',  # LATIN CAPITAL LETTER Q WITH STROKE THROUGH DESCENDER
    (167, 87): 'Q',  # LATIN SMALL LETTER Q WITH STROKE THROUGH DESCENDER
    (167, 88): 'Q',  # LATIN CAPITAL LETTER Q WITH DIAGONAL STROKE
    (167, 89): 'Q',  # LATIN SMALL LETTER Q WITH DIAGONAL STROKE
    (226, 130): 'Q',  # LATIN CAPITAL LETTER Q WITH DOT ABOVE
    (226, 136): 'Q',  # LATIN CAPITAL LETTER Q WITH DOT BELOW
    (230, 129): 'Q',  # LATIN SMALL LETTER Q WITH MACRON
    (230, 130): 'Q',  # LATIN SMALL LETTER Q WITH DOT ABOVE
    (230, 136): 'Q',  # LATIN SMALL LETTER Q WITH DOT BELOW
    (230, 139): 'Q',  # LATIN SMALL LETTER Q WITH STROKE THROUGH DESCENDER AND TILDE
    (232, 179): 'Q',  # LATIN SMALL LETTER Q LIGATED WITH R ROTUNDA
    (232, 180): 'Q',  # LATIN SMALL LETTER Q WITH CENTRAL SLANTED STROKE
    (232, 191): 'Q',  # LATIN SMALL LETTER Q LIGATED WITH FINAL ET
    (234, 209): 'Q',  # LATIN SMALL LIGATURE Q INSULAR V
    (238, 242): 'Q',  # LATIN ENLARGED LETTER SMALL Q
    (239, 12): 'Q',  # LATIN LETTER SMALL CAPITAL Q
    (242, 44): 'Q',  # LATIN CAPITAL LETTER Q WITH STEM
    (0, 75): 'K',  # LATIN CAPITAL LETTER K
    (0, 107): 'K',  # LATIN SMALL LETTER K
    (1, 153): 'K',  # LATIN SMALL LETTER K WITH HOOK
    (29, 11): 'K',  # LATIN LETTER SMALL CAPITAL K
    (30, 48): 'K',  # LATIN CAPITAL LETTER K WITH ACUTE
    (30, 49): 'K',  # LATIN SMALL LETTER K WITH ACUTE
    (30, 50): 'K',  # LATIN CAPITAL LETTER K WITH DOT BELOW
    (30, 51): 'K',  # LATIN SMALL LETTER K WITH DOT BELOW
    (167, 64): 'K',  # LATIN CAPITAL LETTER K WITH STROKE
    (167, 65): 'K',  # LATIN SMALL LETTER K WITH STROKE
    (167, 66): 'K',  # LATIN CAPITAL LETTER K WITH DIAGONAL STROKE
    (167, 67): 'K',  # LATIN SMALL LETTER K WITH DIAGONAL STROKE
    (167, 68): 'K',  # LATIN CAPITAL LETTER K WITH STROKE AND DIAGONAL STROKE
    (167, 69): 'K',  # LATIN SMALL LETTER K WITH STROKE AND DIAGONAL STROKE
    (225, 104): 'K',  # LATIN CAPITAL LETTER K WITH DOT ABOVE
    (229, 104): 'K',  # LATIN SMALL LETTER K WITH DOT ABOVE
    (231, 195): 'K',  # LATIN SMALL LETTER K WITH MEDIUM-HIGH OVERLINE (ACROSS ASCENDER)
    (231, 200): 'K',  # LATIN SMALL LIGATURE K AND LONG S WITH STROKE
    (232, 197): 'K',  # LATIN SMALL LETTER K LIGATED WITH ARM OF LATIN SMALL LETTER R
    (235, 174): 'K',  # LATIN SMALL LIGATURE K AND LONG S
    (235, 219): 'K',  # LATIN LETTER SMALL CAPITAL K WITH DOT ABOVE
    (238, 236): 'K',  # LATIN ENLARGED LETTER SMALL K
    (241, 149): 'K',  # LATIN SMALL LETTER K WITH CURL
    (242, 8): 'K',  # LATIN LETTER UNCIAL K
    (242, 9): 'K',  # LATIN SMALL LETTER K CLOSED FORM
    (242, 33): 'K',  # LATIN SMALL LETTER K SEMI-CLOSED FORM
    (0, 79): 'O',  # LATIN CAPITAL LETTER O
    (0, 111): 'O',  # LATIN SMALL LETTER O
    (0, 186): 'O',  # MASCULINE ORDINAL INDICATOR
    (0, 210): 'O',  # LATIN CAPITAL LETTER O WITH GRAVE
    (0, 211): 'O',  # LATIN CAPITAL LETTER O WITH ACUTE
    (0, 212): 'O',  # LATIN CAPITAL LETTER O WITH CIRCUMFLEX
    (0, 213): 'O',  # LATIN CAPITAL LETTER O WITH TILDE
    (0, 214): 'O',  # LATIN CAPITAL LETTER O WITH DIAERESIS
    (0, 216): 'O',  # LATIN CAPITAL LETTER O WITH STROKE
    (0, 242): 'O',  # LATIN SMALL LETTER O WITH GRAVE
    (0, 243): 'O',  # LATIN SMALL LETTER O WITH ACUTE
    (0, 244): 'O',  # LATIN SMALL LETTER O WITH CIRCUMFLEX
    (0, 245): 'O',  # LATIN SMALL LETTER O WITH TILDE
    (0, 246): 'O',  # LATIN SMALL LETTER O WITH DIAERESIS
    (0, 248): 'O',  # LATIN SMALL LETTER O WITH STROKE
    (1, 76): 'O',  # LATIN CAPITAL LETTER O WITH MACRON
    (1, 77): 'O',  # LATIN SMALL LETTER O WITH MACRON
    (1, 78): 'O',  # LATIN CAPITAL LETTER O WITH BREVE
    (1, 79): 'O',  # LATIN SMALL LETTER O WITH BREVE
    (1, 80): 'O',  # LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
    (1, 81): 'O',  # LATIN SMALL LETTER O WITH DOUBLE ACUTE
    (1, 82): 'O',  # LATIN CAPITAL LIGATURE OE
    (1, 83): 'O',  # LATIN SMALL LIGATURE OE
    (1, 209): 'O',  # LATIN CAPITAL LETTER O WITH CARON
    (1, 210): 'O',  # LATIN SMALL LETTER O WITH CARON
    (1, 234): 'O',  # LATIN CAPITAL LETTER O WITH OGONEK
    (1, 235): 'O',  # LATIN SMALL LETTER O WITH OGONEK
    (1, 236): 'O',  # LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
    (1, 237): 'O',  # LATIN SMALL LETTER O WITH OGONEK AND MACRON
    (1, 254): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
    (1, 255): 'O',  # LATIN SMALL LETTER O WITH STROKE AND ACUTE
    (2, 42): 'O',  # LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
    (2, 43): 'O',  # LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
    (2, 46): 'O',  # LATIN CAPITAL LETTER O WITH DOT ABOVE
    (2, 47): 'O',  # LATIN SMALL LETTER O WITH DOT ABOVE
    (2, 84): 'O',  # LATIN SMALL LETTER OPEN O
    (2, 118): 'O',  # LATIN LETTER SMALL CAPITAL OE
    (29, 15): 'O',  # LATIN LETTER SMALL CAPITAL O
    (30, 82): 'O',  # LATIN CAPITAL LETTER O WITH MACRON AND ACUTE
    (30, 83): 'O',  # LATIN SMALL LETTER O WITH MACRON AND ACUTE
    (30, 204): 'O',  # LATIN CAPITAL LETTER O WITH DOT BELOW
    (30, 205): 'O',  # LATIN SMALL LETTER O WITH DOT BELOW
    (30, 206): 'O',  # LATIN CAPITAL LETTER O WITH HOOK ABOVE
    (30, 207): 'O',  # LATIN SMALL LETTER O WITH HOOK ABOVE
    (167, 76): 'O',  # LATIN SMALL LETTER OE WITH LOOP
    (167, 77): 'O',  # LATIN CAPITAL LETTER OE WITH LOOP
    (167, 78): 'O',  # LATIN CAPITAL LETTER OO
    (167, 79): 'O',  # LATIN SMALL LETTER OO
    (226, 8): 'O',  # LATIN CAPITAL LETTER O WITH OGONEK AND DOT BELOW
    (226, 12): 'O',  # LATIN CAPITAL LETTER O WITH OGONEK AND ACUTE
    (226, 27): 'O',  # LATIN CAPITAL LETTER O WITH MACRON AND BREVE
    (226, 45): 'O',  # LATIN CAPITAL LETTER O WITH DIAERESIS AND CIRCUMFLEX
    (226, 68): 'O',  # LATIN CAPITAL LETTER O WITH LATIN SMALL LETTER E ABOVE
    (226, 70): 'O',  # LATIN CAPITAL LETTER O WITH LATIN SMALL LETTER U ABOVE
    (226, 79): 'O',  # LATIN CAPITAL LETTER O WITH OGONEK AND CURL
    (226, 82): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND MACRON
    (226, 83): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND MACRON AND BREVE
    (226, 85): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND OGONEK
    (226, 87): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND OGONEK AND ACUTE
    (226, 89): 'O',  # LATIN CAPITAL LIGATURE OE WITH ACUTE
    (226, 93): 'O',  # LATIN CAPITAL LIGATURE OE WITH MACRON
    (226, 96): 'O',  # LATIN CAPITAL LIGATURE OE WITH MACRON AND BREVE
    (226, 98): 'O',  # LATIN CAPITAL LIGATURE OE WITH OGONEK
    (227, 211): 'O',  # LATIN CAPITAL LETTER O WITH CURL
    (227, 212): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND CURL
    (230, 8): 'O',  # LATIN SMALL LETTER O WITH OGONEK AND DOT BELOW
    (230, 12): 'O',  # LATIN SMALL LETTER O WITH OGONEK AND ACUTE
    (230, 14): 'O',  # LATIN SMALL LETTER O WITH OGONEK AND CIRCUMFLEX
    (230, 27): 'O',  # LATIN SMALL LETTER O WITH MACRON AND BREVE
    (230, 44): 'O',  # LATIN SMALL LETTER O WITH DIAERESIS AND ACUTE
    (230, 45): 'O',  # LATIN SMALL LETTER O WITH DIAERESIS AND CIRCUMFLEX
    (230, 55): 'O',  # LATIN SMALL LETTER O WITH RING ABOVE
    (230, 67): 'O',  # LATIN SMALL LETTER O WITH LATIN SMALL LETTER A ABOVE
    (230, 68): 'O',  # LATIN SMALL LETTER O WITH LATIN SMALL LETTER E ABOVE
    (230, 69): 'O',  # LATIN SMALL LETTER O WITH LATIN SMALL LETTER I ABOVE
    (230, 70): 'O',  # LATIN SMALL LETTER O WITH LATIN SMALL LETTER U ABOVE
    (230, 71): 'O',  # LATIN SMALL LETTER O WITH LATIN SMALL LETTER V ABOVE
    (230, 79): 'O',  # LATIN SMALL LETTER O WITH OGONEK AND CURL
    (230, 82): 'O',  # LATIN SMALL LETTER O WITH STROKE AND MACRON
    (230, 83): 'O',  # LATIN SMALL LETTER O WITH STROKE AND MACRON AND BREVE
    (230, 85): 'O',  # LATIN SMALL LETTER O WITH STROKE AND OGONEK
    (230, 87): 'O',  # LATIN SMALL LETTER O WITH STROKE AND OGONEK AND ACUTE
    (230, 89): 'O',  # LATIN SMALL LIGATURE OE WITH ACUTE
    (230, 93): 'O',  # LATIN SMALL LIGATURE OE WITH MACRON
    (230, 96): 'O',  # LATIN SMALL LIGATURE OE WITH MACRON AND BREVE
    (230, 98): 'O',  # LATIN SMALL LIGATURE OE WITH OGONEK
    (231, 204): 'O',  # LATIN SMALL LETTER OPEN O WITH MACRON
    (231, 211): 'O',  # LATIN SMALL LETTER O WITH CURL
    (231, 212): 'O',  # LATIN SMALL LETTER O WITH STROKE AND CURL
    (232, 215): 'O',  # LATIN SMALL LETTER O WITH DIAGONAL DIAERESIS
    (232, 222): 'O',  # LATIN SMALL LIGATURE O R ROTUNDA
    (232, 233): 'O',  # LATIN SMALL LETTER O WITH LATIN SMALL LETTER O ABOVE
    (235, 183): 'O',  # LATIN CAPITAL LETTER O WITH CURL AND ACUTE
    (235, 184): 'O',  # LATIN SMALL LETTER O WITH CURL AND ACUTE
    (235, 196): 'O',  # LATIN CAPITAL LETTER O WITH OGONEK AND DOUBLE ACUTE
    (235, 197): 'O',  # LATIN SMALL LETTER O WITH OGONEK AND DOUBLE ACUTE
    (235, 198): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND DOUBLE ACUTE
    (235, 199): 'O',  # LATIN SMALL LETTER O WITH STROKE AND DOUBLE ACUTE
    (235, 200): 'O',  # LATIN CAPITAL LIGATURE OE WITH DOUBLE ACUTE
    (235, 201): 'O',  # LATIN SMALL LIGATURE OE WITH DOUBLE ACUTE
    (235, 205): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND DOT ABOVE
    (235, 206): 'O',  # LATIN SMALL LETTER O WITH STROKE AND DOT ABOVE
    (235, 222): 'O',  # LATIN CAPITAL LETTER O WITH OGONEK AND DOT ABOVE
    (235, 223): 'O',  # LATIN SMALL LETTER O WITH OGONEK AND DOT ABOVE
    (235, 224): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND DOT BELOW
    (235, 225): 'O',  # LATIN SMALL LETTER O WITH STROKE AND DOT BELOW
    (235, 228): 'O',  # LATIN CAPITAL LIGATURE OO WITH DIAERESIS
    (235, 229): 'O',  # LATIN SMALL LIGATURE OO WITH DIAERESIS
    (235, 236): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND MACRON AND ACUTE
    (235, 237): 'O',  # LATIN SMALL LETTER O WITH STROKE AND MACRON AND ACUTE
    (235, 238): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND BREVE
    (235, 239): 'O',  # LATIN SMALL LETTER O WITH STROKE AND BREVE
    (235, 248): 'O',  # LATIN CAPITAL LETTER O WITH DOT ABOVE AND ACUTE
    (235, 249): 'O',  # LATIN SMALL LETTER O WITH DOT ABOVE AND ACUTE
    (235, 250): 'O',  # LATIN CAPITAL LETTER O WITH OGONEK AND DOT ABOVE AND ACUTE
    (235, 251): 'O',  # LATIN SMALL LETTER O WITH OGONEK AND DOT ABOVE AND ACUTE
    (235, 252): 'O',  # LATIN CAPITAL LETTER O WITH STROKE AND DOT ABOVE AND ACUTE
    (235, 253): 'O',  # LATIN SMALL LETTER O WITH STROKE AND DOT ABOVE AND ACUTE
    (238, 240): 'O',  # LATIN ENLARGED LETTER SMALL O
    (239, 173): 'O',  # LATIN SMALL LIGATURE OC
    (239, 221): 'O',  # LATIN ENLARGED LETTER SMALL LIGATURE OE
    (239, 232): 'O',  # LATIN CAPITAL LIGATURE OO WITH ACUTE
    (239, 233): 'O',  # LATIN SMALL LIGATURE OO WITH ACUTE
    (239, 236): 'O',  # LATIN CAPITAL LIGATURE OO WITH DOUBLE ACUTE
    (239, 237): 'O',  # LATIN SMALL LIGATURE OO WITH DOUBLE ACUTE
    (239, 252): 'O',  # LATIN CAPITAL LIGATURE OO WITH DOT BELOW
    (239, 253): 'O',  # LATIN SMALL LIGATURE OO WITH DOT BELOW
    (0, 33): '',  # EXCLAMATION MARK
    (0, 34): '',  # QUOTATION MARK
    (0, 39): '',  # APOSTROPHE
    (0, 40): '',  # LEFT PARENTHESIS
    (0, 41): '',  # RIGHT PARENTHESIS
    (0, 44): '',  # COMMA
    (0, 45): '',  # HYPHEN-MINUS
    (0, 47): '',  # SOLIDUS
    (0, 58): '',  # COLON
    (0, 60): '',  # LESS-THAN SIGN
    (0, 62): '',  # GREATER-THAN SIGN
    (0, 63): '',  # QUESTION MARK
    (0, 91): '',  # LEFT SQUARE BRACKET
    (0, 92): '',  # REVERSE SOLIDUS
    (0, 93): '',  # RIGHT SQUARE BRACKET
    (0, 95): '',  # LOW LINE
    (0, 123): '',  # LEFT CURLY BRACKET
    (0, 124): '',  # VERTICAL LINE
    (0, 125): '',  # RIGHT CURLY BRACKET
    (0, 161): '',  # INVERTED EXCLAMATION MARK
    (0, 166): '',  # BROKEN BAR
    (0, 171): '',  # LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
    (0, 183): '',  # MIDDLE DOT
    (0, 187): '',  # RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
    (0, 191): '',  # INVERTED QUESTION MARK
    (16, 251): '',  # GEORGIAN PARAGRAPH SEPARATOR
    (32, 16): '',  # HYPHEN
    (32, 17): '',  # NON-BREAKING HYPHEN
    (32, 18): '',  # FIGURE DASH
    (32, 19): '',  # EN DASH
    (32, 20): '',  # EM DASH
    (32, 21): '',  # HORIZONTAL BAR
    (32, 22): '',  # DOUBLE VERTICAL LINE
    (32, 24): '',  # LEFT SINGLE QUOTATION MARK
    (32, 25): '',  # RIGHT SINGLE QUOTATION MARK
    (32, 26): '',  # SINGLE LOW-9 QUOTATION MARK
    (32, 27): '',  # SINGLE HIGH-REVERSED-9 QUOTATION MARK
    (32, 28): '',  # LEFT DOUBLE QUOTATION MARK
    (32, 29): '',  # RIGHT DOUBLE QUOTATION MARK
    (32, 30): '',  # DOUBLE LOW-9 QUOTATION MARK
    (32, 31): '',  # DOUBLE HIGH-REVERSED-9 QUOTATION MARK
    (32, 36): '',  # ONE DOT LEADER
    (32, 37): '',  # TWO DOT LEADER
    (32, 38): '',  # HORIZONTAL ELLIPSIS
    (32, 39): '',  # HYPHENATION POINT
    (32, 50): '',  # PRIME
    (32, 51): '',  # DOUBLE PRIME
    (32, 57): '',  # SINGLE LEFT-POINTING ANGLE QUOTATION MARK
    (32, 58): '',  # SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
    (32, 68): '',  # FRACTION SLASH
    (32, 69): '',  # LEFT SQUARE BRACKET WITH QUILL
    (32, 70): '',  # RIGHT SQUARE BRACKET WITH QUILL
    (32, 86): '',  # THREE DOT PUNCTUATION
    (32, 88): '',  # FOUR DOT PUNCTUATION
    (34, 52): '',  # THEREFORE
    (34, 53): '',  # BECAUSE
    (34, 55): '',  # PROPORTION
    (34, 215): '',  # GREATER-THAN WITH DOT
    (39, 230): '',  # LEFT WHITE SQUARE BRACKET
    (39, 231): '',  # RIGHT WHITE SQUARE BRACKET
    (39, 232): '',  # LEFT ANGLE BRACKET
    (39, 233): '',  # RIGHT ANGLE BRACKET
    (42, 253): '',  # PUNCTUATION MARK DOUBLE SOLIDUS
    (46, 0): '',  # RIGHT ANGLE SUBSTITUTION MARKER
    (46, 12): '',  # LEFT UPPER SLANTED STROKE
    (46, 13): '',  # RIGHT UPPER SLANTED STROKE
    (46, 23): '',  # DOUBLE OBLIQUE HYPHEN
    (46, 28): '',  # RIGHT LOWER SLANTED STROKE
    (46, 29): '',  # LEFT LOWER SLANTED STROKE
    (46, 32): '',  # RIGHT VERTICAL BAR WITH QUILL
    (46, 33): '',  # LEFT VERTICAL BAR WITH QUILL
    (46, 34): '',  # TOP LEFT HALF BRACKET
    (46, 35): '',  # TOP RIGHT HALF BRACKET
    (46, 36): '',  # BOTTOM LEFT HALF BRACKET
    (46, 37): '',  # BOTTOM RIGHT HALF BRACKET
    (46, 38): '',  # LEFT SIDEWAYS U BRACKET
    (46, 39): '',  # RIGHT SIDEWAYS U BRACKET
    (46, 40): '',  # LEFT DOUBLE PARENTHESIS
    (46, 41): '',  # RIGHT DOUBLE PARENTHESIS
    (46, 42): '',  # TWO DOTS OVER ONE DOT PUNCTUATION
    (46, 43): '',  # ONE DOT OVER TWO DOTS PUNCTUATION
    (46, 44): '',  # FOUR DOTS PUNCTUATION
    (46, 45): '',  # FIVE DOT MARK
    (46, 46): '',  # REVERSED QUESTION MARK
    (46, 64): '',  # DOUBLE HYPHEN
    (241, 96): '',  # PUNCTUS INTERROGATIVUS
    (241, 97): '',  # PUNCTUS ELEVATUS
    (241, 218): '',  # MIDDLE RING
    (241, 219): '',  # PALM BRANCH
    (241, 224): '',  # MEDIEVAL COMMA
    (241, 225): '',  # PARAGRAPHUS
    (241, 226): '',  # COMMA POSITURA
    (241, 227): '',  # HIGH COMMA POSITURA (SIMPLEX DUCTUS)
    (241, 228): '',  # PUNCTUS WITH COMMA POSITURA
    (241, 229): '',  # COLON WITH MIDDLE COMMA POSITURA
    (241, 230): '',  # THREE DOTS WITH COMMA POSITURA
    (241, 231): '',  # PUNCTUS EXCLAMATIVUS
    (241, 232): '',  # PUNCTUS INTERROGATIVUS HORIZONTAL TILDE
    (241, 234): '',  # PUNCTUS VERSUS
    (241, 236): '',  # SIGNE DE RENVOI
    (241, 240): '',  # PUNCTUS ELEVATUS DIAGONAL STROKE
    (241, 241): '',  # PUNCTUS INTERROGATIVUS LEMNISKATE FORM
    (241, 242): '',  # TWO DOTS OVER COMMA POSITURA
    (241, 244): '',  # VIRGULA SUSPENSIVA
    (241, 245): '',  # PUNCTUS FLEXUS
    (241, 247): '',  # SHORT VIRGULA
    (241, 248): '',  # DISTINCTIO
    (241, 249): '',  # WAVY LINE
    (241, 250): '',  # PUNCTUS ELEVATUS WITH HIGH BACK
    (241, 251): '',  # PUNCTUS ELEVATUS WITH ONSET
}